### ISSUE TITLE
Frontend Code Style

### ISSUE THREAD

**Issue by wobkenh** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#101]
Aktuell sind die vue Dateien im Frontend nicht einheitlich formatiert, z.B. ist teils eine Einrückung von 2 Spaces und teils von 4 Spaces zu finden.

Es sollte ein einheitlicher Codestyle definiert werden - bevorzugt so, dass er von der IDE erkannt/importiert werden kann.

In diesem Issue sollte der Codestyle dann auch in allen Vue Components gerade gezogen werden.

**Comment by wobkenh** [comment]
okay ich sehe gerade, dass eslint:recommended in der package.json eingetragen ist. Meine IDE hat das zuerst nicht erkannt, da ich nur TSLint aktiviert hatte und nicht ESLint. Trotzdem sollte die Formattierung einmal gerade gezogen werden.

**Comment by JonasCir** [comment]
@MichaelSp @wobkenh  Can this be closed then (#193)?

**Comment by wobkenh** [comment]
yes
