### ISSUE TITLE
Client Backend URL in Staging

### ISSUE THREAD

**Issue by wobkenh** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#108]
Das Backend zeigt aktuell noch auf http://35.246.194.158:8080, wenn die App nicht lokal geöffnet ist. In der Staging-Umgebung müsste jedoch https://api.staging.imis-prototyp.de/ aufgerufen werden.

**Comment by MichaelSp** [comment]
ist erledigt, oder?

**Comment by wobkenh** [comment]
Jap.
