### ISSUE TITLE
Benutzerinformation

### ISSUE THREAD

**Issue by wobkenh** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#119]
Das Benutzericon oben rechts in der Navigation sollte klickbar sein. Dort sollte der User dann seine Informationen sehen können. (z.B. Email/Username, Rolle)
Es ist auch denkbar, den Logout dorthin zu verschieben, da im allgemeinen ein Logout immer oben rechts erwartet wird.

**Comment by Jochen-Sch** [comment]
Ist aus meiner Sicht closed weil bereits eingebaut, oder?

**Comment by wobkenh** [comment]
yes
