### ISSUE TITLE
Coronav mit Patient Self-Checkout verbinden

### ISSUE THREAD

**Issue by wobkenh** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#121]
Coronav bietet eine Informationsanwendung für Bürger.

Die Selbst-Registrierung eines Patienten könnte beschleunigt werden, indem eine Mitgabe der Patientendaten von Coronav aus ermöglicht wird. Dazu muss entweder Coronav bei uns eingebunden werden oder die Daten werden an Imis übertragen.

**Comment by t0bska** [comment]
seems to be impossible because of lack of interest in the coronaV team
