### ISSUE TITLE
Patientensuche

### ISSUE THREAD

**Issue by wobkenh** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#122]
Patienten sollten gesucht werden können, falls z.B. eine ältere Person sich keinen QR Code generieren lassen kann und daher im System anderweitig gesucht werden muss.

**Comment by jojo19893** [comment]
for the backend: https://www.baeldung.com/hibernate-search vielleicht 👍

**Comment by wobkenh** [comment]
> for the backend: https://www.baeldung.com/hibernate-search vielleicht +1

Oh, kannte ich noch gar nicht. Sieht aber sehr interessant aus. Ich gebe das mal an Paddy weiter.

**Comment by wobkenh** [comment]
PR ist durch. Wir haben Hibernate Search erstmal nicht eingebaut, da die aktuelle Lösung erstmal ausreichend ist. Sollten wir feststellen, dass da Bedarf für Hibernate Search ist, kann man das ja noch einbauen.
