### ISSUE TITLE
Beruf des Patienten erfassen

### ISSUE THREAD

**Issue by Seal33** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#126]
Insbesondere für medizinisches Personal scheint es von großem Interesse, die Tätigkeit der Infizierten zu erfassen (siehe letzter Abschnitt https://www.tagesschau.de/investigativ/ndr-wdr/pflegepersonal-corona-infektionen-101.html)

Zumindest sollte eine Abfrage in der Art "Arbeiten Sie als medizinisches Personal, wenn ja welcher Art (Pfleger, Arzt, ...)" hinzugefügt werden.

**Comment by t0bska** [comment]
Gut wäre, wenn die Option "Sonstiger Systemrelevanter Beruf" hinzugefügt wird (ggf. mit Freitexteingabe)

**Comment by JonasCir** [comment]
Closing
Es gibt eine vorläufige Funktion um den Beruf in systemrelevanten Bereichen in der Erfassung anzugeben
