### ISSUE TITLE
Make the landing page readable on Mobile Devices

### ISSUE THREAD

**Issue by Seal33** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#129]
Viele Leute werden die Landing Page von Mobilen Geräten aus erstmalig starten. Die landing page sollte dafür optimiert werden. Ggf sollte man erstmal auch den prototypen für mobile deaktivieren, solange dieser dort kaum nutzbar ist

**Comment by wobkenh** [comment]
Ist auf staging
