### ISSUE TITLE
Search Patients with one search string

### ISSUE THREAD

**Issue by jonathangpk** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#131]
When creating a lab test, the user can either scan the patients QR code or search for him in a search bar. The search bar should just one field that can contain a string that can consist of first name, last name, email, phoneNumber.
We could limit the input to just email and telephone number to simplify the logic.

**Comment by wobkenh** [comment]
Da ich das jetzige Suchformular gebaut habe und ähnliche Queries im Backend schon geschrieben habe, würde ich mir das wohl krallen

**Comment by wobkenh** [comment]
Ist das ok, wenn ich mir das kralle? Habe die jetzige Suchmaske implementiert und hätte schon einen Plan, wie man das machen könnte.

**Comment by jonathangpk** [comment]
gerne :)

**Comment by wobkenh** [comment]
Ist in dev.
