### ISSUE TITLE
Change Buildpipeline to autogenerate APIClient using swagger

### ISSUE THREAD

**Issue by jonathangpk** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#136]
The client is now using an autogenerated Client using the swagger docs from the server. Therefore the server has to be run before the build script for the client is executed.

**Comment by jonathangpk** [comment]
Is preferred
The TS client is autogenerated from the swagger json docs using the npm script 'generate:api-client'

The idea is that the typescript client is always in sync with the backend. So when a backend developer implements a breaking change, the build fails while transpiling TS to js. 
For now, we added the auto-generated file to the repo, but this would be an enhancement for the future

@wobkenh  found this package: https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-gradle-plugin
@jojo19893 is also working on this/ thinking about it

**Comment by jojo19893** [comment]
yes I can work on it tomorrow probably _BUT_ we should work on the high importance issues first

**Comment by MichaelSp** [comment]
done, right?

**Comment by jojo19893** [comment]
Nope 
Wir müssen jetzt nochmal drauf schauen mit dem aktuellen deployment sollte es allerdings einfacher werden. 
wir sollten auch nochmal schauen inwiefern es mit swagger noch schöner machen können wir mussten ein paar sachen ändern @jonathangpk .

**Comment by JonasCir** [comment]
Can this issue be closed? @jonathangpk @jojo19893 

#194 was merged
