### ISSUE TITLE
Last Test Result in Patient List

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#139]
Discovered: Staging
Within the Patient Details list view the last status shows "Test eingereicht" despite test result has been recoded.  Might be related to timestamp however . We might need to differentiate between the actual test status ("Test eingereicht"/"Test positiv"/"Test negativ") and the patient status ("Heim-Quarantäne"/"Krankenhaus"/"Intensivstation"/"Entlassen"/"Genesen")

**Comment by wobkenh** [comment]
in staging
