### ISSUE TITLE
Repeated data capture inefficient

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#140]
Whenever a certain step has been done by the respective role, it's required to change app area and go back to capture the next record.. After confirmation of step there shpould be a button to go back to the entry screen of the same area I'm working on as a user.

**Comment by wobkenh** [comment]
Bei Test-Resultat zuordnen und Probe-zuordnen ist das mittlerweile so, dass das Formular zurückgesetzt wird, wenn man es abschickt hat und der Request erfolgreich war. Es müsste also nur noch bei Patient registrieren gemacht werden, wenn ich das richtig sehe.

**Comment by jabrandes** [comment]
Es scheint etwas kniffliger zu sein, ähnliches beim Registrieren von Patienten umzusetzen. Derzeit wird der Benutzer nach der Patientenregistrierung auf die Detailseite des neuen Patienten weitergeleitet. Da wäre eine Art Zwischenansicht mit der ID des generierten Patienteneintrags, sowie den Auswahlmöglichkeiten "Eintrag ansehen" und "Weitere registrieren" ein denkbarer Mittelweg.

**Comment by wobkenh** [comment]
Man könnte auch nach Registrierung des Patienten das Formular clearen und nach oben scrollen. Dort könnte ein Div eingeblendet werden:
- "Patient xy wurde angelegt."
- Links zu weiteren Aktionen für den Patienten (Einsehen, Probe anlegen o.Ä.)
Dann kann der Nutzer entweder auf die nächste Maske weiter oder bei der Registrierung bleiben und noch einen Patienten registrieren.

**Comment by wobkenh** [comment]
Ich habe aufgrund von #151 ebenfalls etwas an der Registrierungsansicht geändert. Ich merge deinen Code mal bei mir rein und beheb die Mergekonflikte.

**Comment by jabrandes** [comment]
Benutzt du den Patient Store aus store/modules/patients.module.ts? Wenn ja, ich habe da den View-spezifischen Code in RegisterPatient.vue hinausgezogen. Macht meiner Ansicht nach mehr Sinn, da der View entscheiden sollte, was nach dem spezifischen Registrierungsvorgang weiter passieren sollte.

**Comment by jabrandes** [comment]
Gibt es eigentlich eine Art Übersichtsgrafik in welcher Reihenfolge welche Formulare üblicherweise gebraucht / ausgefüllt werden? Mir fehlt da gerade der Überblick.

**Comment by wobkenh** [comment]
Zum ersten Kommentar: Den Zugriff auf den Store habe ich an der Stelle entfernt, da der meiner Meinung nach an der Stelle aktuell keinen Mehrwert bietet.

Zum zweiten Kommentar: Es gibt ein PDF mit dem groben Workflow, aber wie genau der Workflow abläuft, das weiß ich auch nicht. Ich folge einfach den Githubissues :smile:

**Comment by wobkenh** [comment]
Siehe PR #166

**Comment by wobkenh** [comment]
Würde das Thema damit abschließen
