### ISSUE TITLE
Gradle test not working in CI

### ISSUE THREAD

**Issue by jonathangpk** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#142]
https://github.com/ImisDevelopers/1_011_a_infektionsfall_uebermittellung/runs/563942844?check_suite_focus=true
![image](https://user-images.githubusercontent.com/33756680/78549775-30f7c280-7803-11ea-9372-e5d7aeacfbf1.png)

**Comment by JonasCir** [comment]
This seems to be fixed

**Comment by JonasCir** [comment]
Showed up again

**Comment by MichaelSp** [comment]
Out of our control. Download of node from central server failed. Code 500 indicates cause on server side. Retry should do it.
Sorry, can't be fixed...
