### ISSUE TITLE
replace username by email everywhere

### ISSUE THREAD

**Issue by jonathangpk** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#147]
having usernames is just confusing and add additional effort
email is sufficient and easier

**Comment by Jochen-Sch** [comment]
Using an email as user name will not work for many doctor offices. Please read the details before inventing changes

**Comment by jonathangpk** [comment]
How do you want to do password resets then? Should just the admin of the institution have a email linked?

**Comment by jonathangpk** [comment]
Would using their private email account violate data policies?

**Comment by JonasCir** [comment]
We should not allow private emails to avoid phishing attacks

**Comment by t0bska** [comment]
Closed for now. Seems to be difficult to use the email-address as username because at some point there will not be an email-address available or multiple patients have the same family email-address.
