### ISSUE TITLE
Patientenerfassung überarbeiten (Durch Patienten selbst)

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#151]
Die UI "Patienten registrieren ist für die Selbstregistrierung nicht geeignet.
Da die Selbstregistrierung voraussichtlich zentraler Bestandteil des Prototypen sein wird, ist sie extrem wichtig.

Die neue UI sollte ohne Login aufgerufen werden können und den Nutzer durch die verschiedenen Fragen geleiten (ähnlich zu [covid-online.de](https://covid-online.de/#/) - als Wizard [die meisten Persönlichen Daten sollten gemeinsam abgefragt werden]). Folgende Funktionen soll sie haben:

- [x] Abfrage von Symptomen wie auf [covid-online.de](https://covid-online.de/#/) Zu erfassende Symptome (Reihenfolge zufällig, unvollständig):

  - Appetit- oder Gewichtsverlust
  - Verlust des Geruchs- oder Geschmackssinnes
  - Fieber
  - Schmerzen
   - Kopfschmerzen
   - Muskelschmerzen
  - Übelkeit
  - Husten
  - Atembeschwerden
   - Atemnot
  - Schnupfen

- [x] Abfrage der Exposition: (Reihenfolge zufällig, unvollständig)
  - Medizinischer Heilberuf
  - Arbeit in medizinischem Labor
  - Aufenthalt in med. Einrichtung < 14 d vor Erkrankung
  - Enger Kontakt mit wahrsch./bestätigt. Fall < 14 d vor Erkrankung
    - in einer medizinischen Einrichtung
    - im privaten Haushalt
    - am Arbeitsplatz
    - andere / sonstige

- [x] Abfrage der Vorerkrankungen / Risikofaktoren: (Reihenfolge zufällig, unvollständig)
  - Herz-Kreislauf (incl. Bluthochdruck)
  - Diabetes
  - Lebererkrankung
  - neurologische / neuromuskuläre Erkrankung
  - Immundefizit inkl. HIV
  - Nierenerkrankung
  - Chronische Lungenerkrankung (z.B. COPD)
  - Krebserkrankung
  - Schwangerschaft
  - Trimester
  - Postpartum (weniger als 6 Wochen) 

- [x] Abfrage der persönlichen Daten: (Reihenfolge zufällig, unvollständig)
   - Titel
   - Vorname
   - Familienname
   - Geburtsdatum
   - Geburtsname
   - Straße
   - PLZ
   - Ort
   - Geschlecht
   - Geburtsland
   - Staatsangehörigkeit
   - Telefon
   - Email
   - Fax
   - Beruf
   - Arbeitgeber (optional)
   - Krankenkassendaten (optional)

**Comment by wobkenh** [comment]
Ich hab mich mal dran versucht.
Den Workflow erreicht man im Staging. Dort gibt es nun neben dem Prototypenbutton einen zweiten Button.

Ich habe mich jetzt erstmal an dem orientiert, was hier im Issue definiert wurde.
Die hier aufgeführten Punkte stimmen aber noch nicht ganz mit dem überein, was das Backend haben möchte:

- fluImmunization (Boolean) => Brauchen wir da eine Checkbox für?
- speedOfSymptomsOutbreak (String) => Da weiß ich nicht, was da rein sollte und ob wir das brauchen
- coronaContacts (Boolean) => Die Unterpunkte mit dem Ort des Kontaktes gibt es im Backend nicht
- riskAreas (String[]) => Ist das überhaupt noch so relevant? Kommt ja eh keiner mehr raus oder rein. Oder brauchen wir dafür noch eine Seite im Workflow?
- weakenedImmuneSystem (Boolean) => Müsste das nicht einfach nur ein Punkt für die Vorerkrankungen sein?
- riskOccupation (String) => Dort gibt es im Backend die Werte NO_RISK_OCCUPATION, FIRE_FIGHTER, DOCTOR, CAREGIVER, NURSE - das müsste entweder im Backend oder hier angepasst werden.
- employer (String) => Gibts noch nicht. Müsste ergänzt werden. Dürfte aber kein Problem sein.

Bei den Fragen kann ja vlt @jojo19893 auch helfen.
Ansonsten gehe ich davon aus, dass es noch einige Wünsche/Verbesserungen zur Oberläche gibt. Immer her damit :)

Übrigens: Die Seite covid-check.de gibt es nicht. War das ein Tippfehler oder haben die die Seite down genommen?

**Comment by t0bska** [comment]
Wow! Das sieht echt gut aus! 😲😀

**Comment by t0bska** [comment]
Edit: die domain lautet [covid-online.de](covid-online.de). Sorry

**Comment by wobkenh** [comment]
Wir sollten uns übrigens auch Gedanken machen, ob wir Symptome und Risiken/Vorerkrankungen im Backend als Enum abbilden - so wie das jetzt ist kann das Frontend da irgendetwas eintragen (@jojo19893 ?)

**Comment by jojo19893** [comment]
I würde eher eine list von string speichern das macht erweiterungen einfacher :)

**Comment by wobkenh** [comment]
Alles klar.

Man müsste sicher noch mal an Frontend/Backend was anpassen (siehe meine Auflistung oben), aber das ist dann ja nicht mehr so dringend.

**Comment by t0bska** [comment]
Todo (UI-Design):

1. Seite Symptome
- [ ] Alphabetisch sortieren
- [ ] Appetits oder Gewichtsverlust trennen
- [ ] Verlust des Geruchs **und oder** Geschmackssinnes 
- [ ] Schmerzen präzisieren
  - Kopfschmerzen
  - Muskelschmerzen
  - Rückenschmerzen
- [ ] Option andere (bei Symptomen)

3. Risiken
- [ ] Alphabetisch sortieren
- [ ] in Vorerkrankungen umbenennen
- [ ] (in**k**l. xxx) überall ändern
- [ ] Trimester entfernen

4. Persönliche Daten

- [ ] Leserichtung von links nach rechts anpassen:
  - Name
  - Vorname
  - Geschlecht
  - Geburtsdatum
  - Straße
  - Hausnummer
  - Postleitzahl
  - Email
  - Telefon
  - Beruf
  - Arbeitgeber (optional)
  - Krankenversicherung
  - Versichertennr.

Notiz: ggf. auf Material Design wechseln (erstmal keine Priorität!)

**Comment by wobkenh** [comment]
Neue Version ist in Staging.
Neben den Amerkungen habe ich auch noch eine PLZ API eingebunden, die ich mal in einem anderen Projekt benutzt habe.

Habe allerdings noch zwei Fragen:
- Option andere ==> Soll da noch ein Freitextfeld hin?
-  in Vorerkrankungen umbenennen ==> Was ist damit gemeint? Aus der Frage würde ich das "Risikofaktoren" lieber nicht streichen, da dort auch z.B. "Schwangerschaft" aufgeführt ist.

**Comment by t0bska** [comment]
> in Vorerkrankungen umbenennen

da hast du recht, das mit Schwangerschaft macht so keinen Sinn. Wir belassen es bei Risiken oder Risikofaktoren.

> Symptome Option andere ==> Soll da noch ein Freitextfeld hin?

kann nichts schaden

**Comment by wobkenh** [comment]
Okay, ist gleich in Staging.
Falls noch was fehlt oder geändert werden muss, gerne her damit. Ansonsten denke ich können wir das Issue schließen. 

Bzgl. Material Design: Am besten ein neues Ticket aufmachen

**Comment by JonasCir** [comment]
@wobkenh 
Hab's mir angeschaut, sieht super aus :) Was noch fehlt ist die Erfassung von systemkritischen Berufen, wie wir sie bei der Patienten Registrierung haben.

**Comment by JonasCir** [comment]
Der nächste Schritt wäre, die Patienten Registrierung die der Arzt macht ähnlich zu der Selbstregistrierung zu gestalten oder? (Falls das nicht sowieso schon der Fall ist)

**Comment by wobkenh** [comment]
Systemkritische Berüfe könnte man bei den persönlichen Daten bei Eingabe des Berufes mit abfrühstücken. Eine Auswahl mit "nicht systemrelevant", "Polizei" usw. und daneben ein Freitextfeld, das nur angezeigt wird, wenn "nicht Systemrelevant".

Die "Patient registrieren" Maske ist noch nicht gleich der Selbstregistrierung. Die einzelnen Masken der Selbstregistrierung müssten noch in Komponenten ausgelagert und in der Patient Registrieren Maske eingebunden werden.

Es sollte noch geklärt werden, ob wir "Wie schnell sind die Beschwerden aufgetreten?" und "Haben Sie für diese Saison eine Influenza-Impfung erhalten?" noch in die Selbstregistrierung aufnehmen oder nicht.

**Comment by t0bska** [comment]
Kann das Textfeld zu andere noch in dieselbe Zeile und der Abstand von der Checkbox nach oben genauso groß wie bei den anderen?

**Comment by wobkenh** [comment]
Done - merge ich gleich nach Staging

**Comment by wobkenh** [comment]
Habe noch die systemkritischen Berufe vergessen - Werde ich heute im Laufe des Tages noch nachholen

**Comment by wobkenh** [comment]
Kommt in 5-10min nach Staging. Falls keine Anmerkungen sind, bitte Ticket schließen.

**Comment by JonasCir** [comment]
Sieht richtig gut aus @wobkenh ! :) 
@t0bska kannst du nochmal drüber schauen? 
Ansonsten denke ich wir können das hier zu machen und Verbesserungen/Bugs separat tracken falls sie auftauchen

**Comment by t0bska** [comment]
sehr gute Arbeit!
