### ISSUE TITLE
Rework Readme

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#156]
Für neue Teammitglieder ist die Readme z.z. nicht besonders aufschlussreich.
Insbesondere eine **funktionierende Anleitung**, wie man den dev-Stand lokal zum Laufen bringt und an Backend und Frontend arbeiten kann fehlt.

**Comment by Seal33** [comment]
Bitte auch beachten, dass wir eine Anleitung für Linus *und* Windows haben

**Comment by TheJKM** [comment]
Einige Infos zum derzeitigen Problem (getestet unter macOS und Linux):

Aufsetzen einer Dev-Umgebung scheitert am Punkt 7 (`./gradlew bootRun`). Fehlermeldung besagt:
`Web server failed to start. Port 80 was already in use.`
zunächst kein Wunder, da Port 80 bereits durch einen Docker-Container belegt wird, der in Schritt 3 gestartet wurde. Allerdings tritt der Fehler auch auf, wenn ich Docker auf Port 81 umbiege (kein anderer Service lauscht auf Port 80).

**Comment by MichaelSp** [comment]
Sollte mit https://github.com/ImisDevelopers/1_011_a_infektionsfall_uebermittellung/pull/150 gelöst sein. Bitte um Review

**Comment by TheJKM** [comment]
Habe immer noch das selbe Problem. Fange morgen nochmal frisch an, hab heute ziemlich viel ausprobiert.

**Comment by TheJKM** [comment]
Kann jetzt bestätigen: das Vorgehen aus feature/build-system funktioniert.

**Comment by wobkenh** [comment]
Da feature/build-system gemerged wurde, mache ich das hier mal dicht.
Falls irgendwelche der Anweisungen in der readme noch nicht funktionieren, kann das Issue wieder eröffnet werden oder ein neues aufgemacht werden
