### ISSUE TITLE
Cloud Credits

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#157]
Hier findet ihr eine Übersicht über die Resourcen die wir zur Verfügung stellen: https://docs.google.com/document/d/17eODy-Jq7yPE8PiVXKWK7pUePc4cOOG0YJ-Rhc7sdyg/edit

Falls ihr eure $300 Google Cloud Free Trial credits bereits verbraucht hab könnt ihr über dieses Formular einen voucher für weitere $250 beantragen: https://forms.gle/hpgDtvaUkWfPwNDHA

**Comment by MichaelSp** [comment]
Google has been contacted... waiting for answer.
In the mean-time we scaled our cluster down to 3 nodes and one DB to reduce consts

**Comment by jojo19893** [comment]
Im Zuge dessen haben wir auch das deployment komplett überarbeitet und haben nochmal wesentlich geld gespart
Danke für den super Einsatz @MichaelSp

**Comment by MichaelSp** [comment]
Wir sind jetzt auf 2-4EUR/Tag runter. Damit kommen wir noch min. 2 Monate weit. 
Danach hätte ich die Möglichkeit kostenlos in das Rechenzentrum von einem Freund nach FRA zu kommen. 
Die nächsten $250 gibt es nur, wenn wir auf einen Billing-Account wechseln. 
Ich werde das weiter beobachten und ggf Maßnahmen ergreifen damit die Platform online bleibt
