### ISSUE TITLE
Vereinfachung deployment und CI

### ISSUE THREAD

**Issue by jojo19893** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#161]
Aktuell laufen wir auf kubernetes und deployen zwei seperate aritfakte.
Meiner meinung nach sollten wir drüber nachdenken wie wir ein einziges jar deployen können das frontend und backend enthält.
Das würde auch das deployment vereinfachen _UND_ billiger machen weil wir wahrscheinlich einfach eine mini-VM brauchen würden + datenbank. 
Ich kann mich sehr gerne darum kümmern dass wir ein einziges gradle deployment jar bekommen bzw ein einziges docker file bauen ABER jemand müsste sich das deployment einmal anschauen 
(@MichaelSp) 
Wir sollten schauen das wir damit relativ schnell in die Gänge kommen insbesondere um kosten zu sparen.

**Comment by jojo19893** [comment]
Zusätzlich muss noch die ` index.ts` adjustiert werden dass es die richtige host-url nimmt

**Comment by jojo19893** [comment]
sollten wir unter umständen auf cloud-run delployen (https://alexolivier.me/posts/deploy-container-stateless-cheap-google-cloud-run-serverless)

**Comment by MichaelSp** [comment]
Klingt gut. Habe ich noch keine Erfahrung mit. Schau ich mir heute mal an

**Comment by MichaelSp** [comment]
Wir haben jetzt 1 deployment. Das Cloud-Run-Thema ist immer noch eine option die das ganze billiger machen würde. Ist aber erstmal on hold: #163
