### ISSUE TITLE
Cleanup Mapping Infrastructure

### ISSUE THREAD

**Issue by jojo19893** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#162]
Aktuell ist unser code im backend relativ mit boilercode übersäht insbesondere um DTOs in andere Objekte fürs Frontend zu bekommen.
Wir sollten erwägen ob wir bspw [Mapstruct](https://mapstruct.org/) nutzen um etwas von diesem code loszuwerden.

**Comment by JonasCir** [comment]
@jojo19893 @jabrandes  Can this be closed? (#198 )
