### ISSUE TITLE
Landing Page: Schreiben, dass wir bei Solution Enabler dabei sind

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#164]
Das muss unbedingt auf dev und master!

https://wirvsvirushackathon.org/weiterfuehrung-2/

**Comment by wobkenh** [comment]
Hier schon mal das Solution Enabler Logo, falls das benötigt wird:
https://wirvsvirushackathon.org/wp-content/uploads/2020/03/Solution-Enabler.png

**Comment by wobkenh** [comment]
done

**Comment by JonasCir** [comment]
Danke! :)
