### ISSUE TITLE
Random Bit in die ID Ermittlung

### ISSUE THREAD

**Issue by jewelt** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#171]
Momentan wird die ID eines Patienten aus dem Vornamen, Nachnamen, PLZ und dem Geburtstag gebildet. Dies kann allerdings zu Problem führen, da so potentiell der PK verletzt wird.

**Comment by JonasCir** [comment]
@jewelt 
Ich habe das Bauchgefühl, dass wir hier vorsichtig sein müssen :)

Wenn wir jetzt Randomness  einführen, dann können wir eigentlich direkt eine Version 4 UUID verwenden, da liegt die colission probability bei 2.71 x 10^18

Falls wir uns für den aktuellen Weg entscheiden, würde ich zumindest ein CPRNG verwenden.

Was meinst du @jojo19893 ?

**Comment by MichaelSp** [comment]
Ich bin auch für Random. Allerdings ist UUID-v4 etwas lang für manuelle Eingaben. Wenn der Prozess das vorsieht, sollten wir was kürzeres nehmen. Da wurden schon systeme erwähnt -> #94

**Comment by jewelt** [comment]
Die ID ist ja immer noch 8 Stellen lang... Habe ja nur eingebaut, dass randomness in die Hash-Ermittlung eingebaut wird. Ansonsten hätte es keine zwei Heinrich Müller in Berlin, die zufällig am gelcieh Tag geboren sind, geben dürfen. Also das heißt die Eingabe bleibt gleich lang.

**Comment by jewelt** [comment]
Das lag daran, dass der Hash nur anhand des Vornamens, Nachnamens, PLZ und Geburstag gebildet wurde...

**Comment by wobkenh** [comment]
Geschlossen, da gemerged
