### ISSUE TITLE
Rework UI "Patient registrieren" (Arzt)

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#176]
Abgefragt werden sollten vorerst folgende Daten (auf sinnvolle Reihenfolge achten):

- Titel
- Name
- Vorname
- Geschlecht
- Geburtsdatum
- Anschrift
  - Straße
  - PLZ
  - Ort
- Verstorben ja / nein
  - verstorben Datum
- Telefon
- E-Mail
- Aufenthaltsort (falls abweichend von Anschrift)
  - Straße
  - PLZ
  - Ort

- Medizinischer Heilberuf?
- Arbeit in medizinischem Labor
- PatientIn arbeitet in Gemeinschaftseinrichtung (z.B. Schule, Kinderkrippe, Heim, sonst. Massenunterkünfte (§§34 und 36 Abs. 1 IfSG))
- Betreuung in Gemeinschaftseinrichtung für Kinder oder Jugendliche, z.B.Schule, Kinderkrippe (§33 IfSG)
- Aufenthalt in med. Einrichtung < 14 d vor Erkrankung

- Art der Erkrankung / Erreger (vorausgefüllt SARS-nCoV-2, nicht änderbar)
- Erkrankungsdatum
- Meldedatum
- Art der Meldung / Fallstatus: (Verdacht / klinische Diagnose [bestätigt] / Erkrankung ausgeschlossen)

- Labor wurde mit Erregerdiagnostik beauftragt?
  - Name des Labors
  - Ort des Labors
  - Datum der Probenentnahme

- PatientIn Hospitalisiert?
  - seit
  - Intensivstation?

- Exposition:
  - enger Kontakt mit Wahrscheinlichkeit. / best. Fall < 14 d vor Erkrankung
  - Setting für den Kontakt (in einer medizinischen Einrichtung, im privaten Haushalt, am Arbeitsplatz, andere / sonstige)

- Risikofaktoren:
  - chronische Lungenerkrankung (z.B. COPD)
  - Diabetis
  - Schwangerschaft
  - Neurologische / Neuromuskuläre erkrankung
  - Herz-Kreislauf (inkl. Bluthochdruck)
  - Lebererkrankung
  - Immundefizit inkl. HIV
  - Krebserkrankung
  - Trimester
  - Postpartum (<6 Wochen)

- Symptome:
  - Akutes schweres Atemsyndrom (ARDS)
  - Beatmungspflichtige Atemwegserkrankung 

*(Diese Liste beinhaltet nur die Daten, welche zwingend erfasst werden müssen und wird noch ergänzt werden, was kein Grund sein soll, diesen Issue nicht zu bearbeiten. Die Daten (außer Aufenthalt in Risikogebieten), welche jetzt schon in dem Formular erfasst werden, dürfen auch weiterhin erfasst werden und müssen nicht entfernt werden :-) )*

Bitte auf Benutzerfreundlichkeit achten :-) Zielgruppe sind Ärzte. Das bisherige Formular muss in weiten teilen ersetzt werden.

**Comment by wobkenh** [comment]
Würde einen Stepper wie bei der Selbstregistrierung empfehlen (mit mehr Schritten). Sollen Teile der Selbstregistrierung übernommen werden (z.B. z.B. die Symptomauswahl, Stammdaten)? Oder eher im Stil lassen wie es aktuell ist?

**Comment by t0bska** [comment]
Würde ich tatsächlich nicht mit Stepper machen, sondern zum Ausklappen wie bisheriges UI, ich glaube, das ist für einen Arzt besser und schneller zu bedienen, nachdem man das 1-2x gemacht hat. Sollte aber @HellerDominik am besten mal drüber schauen oder so.

**Comment by wobkenh** [comment]
Ich habe die benötigten Felder eingebaut. Ist noch nicht in Staging, weil gerade das Deployment Richtung Staging nicht geht.

Und über Usability kann sich @HellerDominik dann ja mal Gedanken machen ;)

**Comment by wobkenh** [comment]
Ist übrigends mittlerweile in Staging angekommen

**Comment by JonasCir** [comment]
@t0bska @wobkenh 
Was fehlt bei dem issue noch?

**Comment by wobkenh** [comment]
Von meiner Seite fehlt nichts mehr.

**Comment by JonasCir** [comment]
Closing
