### ISSUE TITLE
Quarantänestatus

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#179]
@wobkenh merkt an, dass es noch keine Infos dazu gibt und wahrscheinlich auch noch nichts dazu im backend steht.

**Comment by JonasCir** [comment]
@LeonardKoll Anscheinend gibt es noch keine Möglichkeit einen Patienten in Quarantäne zu schicken.

Dazu müsste (ohne Anspruch auf Vollständigkeit):

- [ ] Quarantäne im Backend/DB implementiert werden
- [ ] ein entsprechendes PatientEvent erstellt werden (Start/Ende der Quarantäne)
- [ ] ein API Endpunkt erstellt werden, um einem Patienten Quarantäne anzuordnen
- [ ] das Frontend in der Gesundheitsamt Übersicht eine entsprechende Option einfügen (@jonathangpk )

**Comment by Jochen-Sch** [comment]
Der Quarantäne Status eines Patienten (Infektions-Falles) ergibt sofern eine Quarantäne angeordnet und noch nicht beendet wurde (gemäss §30 Infektionsschutzgesetz).
Systemtechnisch könnten wir da durch Events abbilden und den Status aus den vorliegenden Events ermitteln 
Event 1: Quaratäne Anordnung -> Quarantäne-Status: Ja
Event 2: Quarantäne Entlassung -> Quarantäne-Status: Nein
Alternativ könnten wir den Quarantäne-Status als explizites Feld abbilden dessen Wert durch die entsprechenden Aktionen gesetzt bzw gelöscht (oder auf false gesetzt) wird.
Zu Bedenken gilt an dieser Stelle dass es viele weitere Events geben kann die analog funktionieren (Krankenhaus Status, Intensiv-Status, Beatmungs-Status, ... in Zukunft könnten weitere hinzukommen). Einzelne Attribute in der DB sind dann eher ungünstig.

Info: Quarantäne Anordnung ist aktuell nicht Teil des Pilotierungsumfangs, was nicht heissen soll, dass man es auf Prototype Branch schon mal baut

**Comment by LeonardKoll** [comment]
Wem obliegt es, jemanden in Quarantäne zu senden? Arzt? Amt?

**Comment by JonasCir** [comment]
Dem Gesundheitsamt :)
