### ISSUE TITLE
Enforce review + approval on each PR

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#180]
Title says it all

**Comment by MichaelSp** [comment]
I'm generally not a big fan of restrictions. I'd only implement that if really necessary. Currently I don't feel the need for it...

**Comment by JonasCir** [comment]
@jojo19893 Das ist doch passiert oder ? :)

**Comment by MichaelSp** [comment]
Ja es ist passiert, aber es gibt meiner Meinung nach keinen Konsens dafür. Ich habe das für nächsten Dienstag mal auf die Agenda gesetzt. Ich würde mir einen Diskussion zu dem Thema wünschen.
