### ISSUE TITLE
Geburtsdatumsfelder ändern

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#183]
Das Geburtsdatum liegt oft weit in der Vergangenheit. Mit dem aktuellen Date-Picker ist das relativ aufwendig. Daher: Placeholder bitte in Datumsformat ändern und Möglichkeit hinzufügen, das Datum einzugeben statt den Date-dicker zu verwenden.
Betrifft: UI Patienten registrieren, Patienten-Selbstregistrierung

**Comment by jabrandes** [comment]
Soweit ich weiß kann man auch beim DatePicker per Text ein Datum eingeben. Was ich da derzeit bemängeln würde wäre das Datumsformat, da wir doch in Deutschland eher das Format DD.MM.YYYY haben. Zudem wäre die Frage, ob man den Picker direkt beim Focus aktiviert, da man scheinbar erst ein Datum eingeben kann wenn der ausgeklappt ist.

**Comment by wobkenh** [comment]
Kann das Datumsformat wohl eben ändern, während ich #176 bearbeite.
Das mit dem Ausklappen bei Fokus kann ich mir dann auch anschauen.

**Comment by jabrandes** [comment]
Ausklappen bei Fokus funktioniert scheinbar nur über das `open`-Prop vom DatePicker. Ich habe zumindest keine andere API in Form von Methoden ermitteln können, mit deren Aufruf man das mal eben machen könnte.
