### ISSUE TITLE
Schnellbearbeitung von Tests

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#185]
Wizard anstelle des bisherigen Probe Zuordnen (testing_site)

1. Patientendaten eingeben
  - Patientendaten:
    - ID (falls bekannt)
    - Name, Vorname
    - Geschlecht
    - Geburtsdatum
    - Hauptwohnsitz: Straße, Hausnr, PLZ, Ort
    - Telefon
    - E-Mail
    - Derzeitiger Aufenthaltsort (falls abweichend): Straße, Hausnr, PLZ, Ort
    - Datenübermittlung an Hausarzt (wenn check, klappen sich die weiteren Felder aus): Name, Ort / Adresse [i.d.R. reicht eingabe des Ortes aus, weitere Adress-Daten kann der Patient oft sowieso nicht direkt liefern], Telefon, Fax, E-Mail
    - Symptome: Erkältungssymptome, Fieber, Kontakt zu Corona-Infizierten, Wurde bereits ein Corona-Test durchgeführt?
  - Sobald ID angegeben, werden bekannte Daten vervollständigt, es wird klar erkennbar angezeigt, ob ein Test angeordnet wurde
  - Sobald pers. Daten angegeben werden Vorschläge gemacht, welcher Patient es sein könnte, den kann man dann anklicken und bekannte Daten werden vervollständigt, es wird klar erkennbar angezeigt, ob ein Test angeordnet wurde
  - Button "Test durchführen" zum weiterkommen
  

2. Test durchführen
  - Auswahl Material (Optionen: Abstrich, andere; Abstrich, mehrere; Blut / Serum;  Nasenabstrich; Rachenabstrich; andere / sonstige
  - Auswahl Ziel-Methode (Optionen: Antigennachweis; Antikörpernachweis;  Nukleinsäurenachweis (z.B. PCR); Virusisolierung; andere /sonstige)
  - Checkbox: Ist schnelltest
  - Textfeld Probennummer
  - Textfeld Kommentar

3. Daten anzeigen
  - Zeigt alle zuvor angegebenen Daten nochmal an
  - Option, diese zu drucken
  - Button nächsten Patienten erfassen

**Comment by wobkenh** [comment]
Soll die bestehende "Probe Zuordnen" Seite so bestehen bleiben, wie sie aktuell ist? Oder soll sie mit diesem Ticket erweitert/ersetzt werden?

Ist mit Wizard ein Stepper wie bei der Selbstregistrierung gemeint oder lieber wie bei der Arzt-Patientenerfassung? Ich würde letzteres vorschlagen.

Soll 3. als Bestätigungsmaske dienen? Ansonsten könnte man die Bestätigung, die auch jetzt schon nach dem Speichern angezeigt wird, um weitere Patientendaten und den einen Drucken-Button ergänzen.

Implementierungshinweise:
zu 1.: 
- Mit  #176 kommt eine "PatientStammdaten" Komponente, die man hier verwenden könnte. Man müsste aber wsl ein change output event definieren, um Vorschläge für existierende Patienten zu machen
- Symptome sind in `symptoms.ts` gepflegt.
- Während der Auswahl des Hausarztes könnte man unter Umständen anhand der in IMIS vorhandenen User mit Rolle "DOCTOR" Vorschläge machen.

**Comment by t0bska** [comment]
Wird gleich einen neuen, konkreteren Issue geben, der deine Fragen auch beantwortet.

**Comment by lordpomeroy** [comment]
@t0bska ist das noch aktuell? Wenn ja, passt das noch zu dem aktuellen Prozess/den aktuellen Formularen?

**Comment by t0bska** [comment]
In Teilen nicht mehr aktuell.
