### ISSUE TITLE
Datenbank: Fälle, Meldungen und Events

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#191]
Ähnlich, wie in #181 vorgeschlagen, sollte die Datenstruktur so geändert werden. Im ersten Schritt bedeutet das, folgenden Prozess besser abzubilden:

Es gibt Patienten. Diese Patienten können eine oder über die Zeit auch mehrere meldepflichtige Erkrankungen (=Fälle) haben. Ein Fall folgt immer aus einer Meldung, welche dann auch weitere Daten (z.B. Symptome, Test-Anordnungen / Durchführungen / Laborergebnisse) liefert sowie persönliche Daten des Patienten und Vorerkrankungen, welche unabhängig von dem Fall direkt für den Patienten und potentiell auch für weitere Fälle des Patienten gelten.

Dabei muss darauf geachtet werden, dass sichergestellt ist, dass immer nachvollzogen werden kann, wer bzw. auch welche Meldung welche Daten eingetragen / geändert hat und jeder seine eigenen Meldungen sehen kann, aber nicht die Daten (Aufnahme eventuell name, Geburtsdatum & Co.), die erst in späteren oder anderen Meldungen hinzugekommen / geändert worden sind. Das Gesundheitsamt hat natürlich Zugriff auf alle Daten.

Als Referenz können die Vorschläge aus #181 gelten. Bei Fragen gern fragen.

**Comment by wobkenh** [comment]
Kann das wohl im Zusammenhang mit #137 und #139 erledigen.

**Comment by wobkenh** [comment]
> Meldungen sehen kann, aber nicht die Daten (Aufnahme eventuell name, Geburtsdatum & Co.), die erst in späteren oder anderen Meldungen hinzugekommen / geändert worden sind.

Darf ich fragen, warum? Wenn ich den Patienten sehen kann, warum sollte ich nicht die aktuelle Adresse des Patienten sehen können? Meiner Meinung nach sollte sowas entweder ganz oder gar nicht sein. Entweder er sieht die aktuelle Adresse des Patienten oder eben nicht. Bspw. wenn der Hausarzt die Adresse nicht pflegt und das von einer anderen Stelle nachgeholt wird, warum sollte der Hausarzt das nicht sehen könne, obwohl er doch für den Patienten zuständig ist? 

Falls es darum geht, dass z.B. Teststellen nach dem Test nicht mehr auf Ewigkeit die Patientendaten sehen sollen - da würde ich eher vorschlagen, dass die Teststellen nur X Tage nach dem Testergebnis noch auf die Patientendaten zugreifen können (für eventuelle Rückfragen?) und nach diesem Zeitraum bei Auflistung der Tests als Patient nur noch die ID und vlt. der Name angezeigt wird. Das ist deutlich einfacher umzusetzen, als bei den Events anhand der Timestamps irgendwelche alten Daten herauszufriemeln.

**Comment by t0bska** [comment]
> Darf ich fragen, warum? Wenn ich den Patienten sehen kann, warum sollte ich nicht die aktuelle Adresse des Patienten sehen können?

Datenschutzgründe. Andernfalls müsste man das Einverständnis des Patienten einholen, da das Gesundheitsamt oder ein anderer Arzt Daten quasi an den Hausarzt übertragen würde. Das Gesundheitsamt darf natürlich alles sehen, jeder (auch die Teststation) muss sehen können, was er / sie _selbst_ gemeldet hat. Weitere Daten dürfen (leider) nicht sichtbar sein.

**Comment by wobkenh** [comment]
#137 und #139 habe ich gleich durch, aber dieses Issue hat es echt in sich. Ich habe auf dem Branch feature/191-cases-events angefangen. Wenn da jemand weitermachen oder neu anfangen möchte, würde ich ihm den Vortritt lassen. Ansonsten muss ich die nächsten Tage schauen, wie viel Zeit ich habe.

**Comment by JonasCir** [comment]
@MariusGiebenhain Willst du mal schauen ? :)

**Comment by MariusGiebenhain** [comment]
ich bin es gerade am durchschauen, bin nicht eingearbeitet in die JPA-Umgebung allerdings

**Comment by MariusGiebenhain** [comment]
Hier eine grobe Idee wie das als ER aussehen würde:
https://dbdiagram.io/d/5e98776c39d18f5553fdb726

- die Trennung doctor/patient ist zur besseren Verständlichkeit vorgenommen/würde für weitere Verknüpfungen nach außerhalb gebraucht werden)
- address ist nur ein Beispiel für weitere Informationen die in information eingefügt werden könnte
- Bin noch nicht ganz sicher wie man Vorerkrankung am besten modeliert, spricht etwas dagegen die einfach über case zu erfassen?

**Comment by wobkenh** [comment]
Würde Vorerkrankungen eher an den Patienten hängen, da die sich nicht ändern, auch wenn der Patient einen neuen Case bekommt

**Comment by MariusGiebenhain** [comment]
Aber die können von einem Doktor für einen Patienten gemeldet werden oder? 
Sie als Meldung zu speichern würde deshalb da unsere Datenschutzansrüche erfüllen, wenn nur der Melder und der Patient auf die Meldung über eine Vorerkrankung zugreifen dürfen

**Comment by jojo19893** [comment]
naja man kann es einfach in einen `@OneToMany` und dann einen `InformationContainer` packen und den noch mit einem `validFrom` timestamp versehen.

**Comment by wobkenh** [comment]
Müsste der `InformationContainer` eigentlich an einem `user` hängen oder an einer `institution`? Ich kann mir vorstellen, dass wenn z.B. eine Arzthelferin die Daten aufnimmt, der Arzt das dann auch sehen darf. Allerdings kann ich mir auch vorstellen, dass in einer Klinik vlt. nicht jeder Zugriff auf alles haben sollte. Also vlt beides? Oder man macht die Verknüpfung zum User und macht den Zugriff auf die Institution bei Bedarf über den User.

**Comment by MariusGiebenhain** [comment]
Gute Frage - du hast Recht, dass Informationen vllt wirklich besser an Institutionen gebunden werden - vllt kann man das bei Kliniken nach Abteilung machen? Also eine Abteilung entspricht einer Praxis?

Hat irgendwer hier juristischen Hintergrund bzgl Datenschutz? 
Sollen wir vllt generell mal eine Discord Konferenz starten zu dem Thema? Habe wie angedeutet paar Ideen zur Umsetzung, aber noch nie zuvor mit JPA gearbeitet und fühle mich deshalb unwohl als erste Anwendung direkt so eine eher komplexe Aufgabe anzugehen - vllt können wir dann ja alle zusammen eine Runde nochmal Brainstormen und effektiv Teil-Aufgaben verteilen

**Comment by wobkenh** [comment]
Ich habe mal auf Branch feature/191-cases-events weitergemacht und eine `PatientInformation` eingeführt (das ist dann der `InformationContainer` für einen Patienten). Bei der Abfrage von Patienten habe ich das jetzt erstmal so gemacht, dass Informationen eingesehen werden können, wenn der verknüpfte User der eigenen Institution angehört. Kann man immer noch umbauen, falls benötigt.

**Comment by wobkenh** [comment]
Ich könnte im Backend Hilfe gebrauchen bei der Umsetzung der Patientensuche.
Am besten sollten da direkt nur die Fälle von der Datenbank selektiert werden, die der Nutzer auch sehen darf. Dies ist insbesondere wichtig für die count-Endpunkte (für Pagination im Frontend), da hier bisher einfach ein `count(*)` gemacht wird und es ineffizient wäre, sich erst alle Patienten in den Speicher zu fressen, die auf die Suchkriterien anschlagen.

**Comment by MariusGiebenhain** [comment]
wonach ist definiert, auf welche Patienten ein Nutzer Zugriff hat? Sind das lediglich die zu denen der Nutzer selbst Infos eingetragen hat? In diesem Fall müsste könnte man ja eine Subabfrage nutzen, die ausgibt für welche Patienten(-Ids) der Nutzer Informationen hinzugefügt hat und ein inner join der Patienten darauf machen?
Die Suche wäre dann auf dieses Ergebnis

**Comment by JonasCir** [comment]
@LeonardKoll Gibt es bezgl. Fälle, Meldungen und Events noch Probleme oder Unstimmigkeiten?

**Comment by LeonardKoll** [comment]
Mit den Tickets #460 #461 #466 sollte das erledigt sein.
Siehe auch:
https://docs.google.com/document/d/1cbrvP_LKiFH2Ca1kU5zK3Iqb1ji5pSYMae_AEdaXX6E/edit
