### ISSUE TITLE
Institution Registration Form Controls partially un-editable by click

### ISSUE THREAD

**Issue by jabrandes** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#199]
Most of the bottom section controls of the current registration form for new institution accounts cannot be brought into text-editing mode by point-and-click selection, only when using keyboard shortcuts. Clicking on the text boxes and the institution type combobox does not seem to have any effect: No text cursor is displayed and typed text does not show up in the respective control.

This bug was encountered using a recent Firefox build (75.0 on a 64-bit machine).

**Comment by eriklueth** [comment]
Merged Fix
