### ISSUE TITLE
Create prototype-branch

### ISSUE THREAD

**Issue by Seal33** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#202]
Wir brauchen einen Branch auf welchem nur der Pilot mit den zugehörigen features läuft (ausdrücklich ohne sonstige features).

Dieser sollte am besten auch auf einer weiteren subdomain laufen, z.B. pilot.imis-prototyp.de

**Comment by MichaelSp** [comment]
Pilot up and running -> https://pilot.imis-prototyp.de/
