### ISSUE TITLE
Character Encoding fehlerhaft

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#206]
<img width="139" alt="image" src="https://user-images.githubusercontent.com/43952751/79638196-a5781d00-8184-11ea-868f-05ad1ee0fd87.png">
Siehe Bild. (Hier aus Gesundheitsamt -> Account)

**Comment by jabrandes** [comment]
Der Staging-Prototyp läuft auf Windows, oder? Sieht nämlich ganz so aus, als ob das Charset-Problem vom Betriebssystem des Servers abhängt. Windoof verwendet ja leider sein eigenes Encoding und nicht UTF-8, in dem die Testdaten für das Department of Health verfasst sind.

**Comment by MichaelSp** [comment]
Serverseitig läuft alles auf linux/docker.

**Comment by jabrandes** [comment]
Ich glaube dennoch, dass es mit dem Einlesen der Testdaten zu tun haben wird. Im Code des Servers werden die Testdaten immer im nativen Encoding eingelesen, und sofern Umlaute und Sonderzeichen darin nicht als Codepoint ausgeschrieben werden (`\u...`-Notation, wird konsequent bei den Personendaten verwendet) kommt es zu den Anzeigeproblemen.
