### ISSUE TITLE
In Detailansicht sind alle Patienten divers

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#209]
Korrektes Geschlecht anzeigen

**Comment by JonasCir** [comment]
@wobkenh Da ging teilweise etwas schief:
server/src/main/resources/sample_data/persons/person62.json

Da sind Frauen mit Männernamen! Kommt öfter vor.

**Comment by JonasCir** [comment]
Siehe commit 928504e2a1193bb67f221c211ed365a2d08bb734

**Comment by wobkenh** [comment]
Da der Branch für #191 voraussichtlich nicht mehr weiterverfolgt wird, mache ich für das Ticket mal einen neuen Branch und zieh die Änderung rüber.
