### ISSUE TITLE
Migration to Spring Security ACL

### ISSUE THREAD

**Issue by jabrandes** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#211]
The server backend is not requesting authentication for some routes accessing patient data. These include:

- `GET /api/patients`
- `GET /api/patients/{id}`

This problem might also exist for routes not related to patient data, so a review of API-routes related to access rights is recommended.

**Comment by jojo19893** [comment]
the security config has to be adjusted in backend
if you have time  @LeonardKoll maybe look at it? 
Otherwise I will do it this weeked 
Reference `SpringSecurityConfig`

**Comment by LeonardKoll** [comment]
Die von @jabrandes angemerkte Lücke sollte im Zusammenhang mit der Migration auf Spring Security ACL geschlossen werden.
Siehe auch [Backend Konzept auf Google Docs unter "Security"](https://docs.google.com/document/d/1lHQOWxgB4g7TFf3fyKaEahS0qp1ckKRW_FBPHKiiaKw).

**Comment by jojo19893** [comment]
Added PR fix
