### ISSUE TITLE
Self Register Form Changes

### ISSUE THREAD

**Issue by jonathangpk** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#222]
Layout:
- [x] after going to the next page in the registration it should scroll up automatically
- [x] reduce whitespace usage to reduce scrolling as much as possible

Risiken:
- [x] remove "Postpartum" as risk
- [x] add "Fettleibigkeit (Adipositas)
- [x] Raucher (evtl. mit angabe zur anzahl in zigaretten / tag)

Personal Data
- [x] Gender should be medical gender -> remove "diverse"
- [x] Street and Streetnumber in on input
- [x] Add country field
- [x] Add Nationality
- [x] rename "kein systemrelevanter Beruf" to "keiner der genannten Berufe"

**Comment by jabrandes** [comment]
The proposal to combine street address and house number into one input control raises the question whether such change should be reflected in the server-side storage of the address data. Currently, street address and house number are also stored separately in the database. I'm quite optimistical we can keep it that way by using a regular expression to split the combined control's input value into street and house number component, but is that what we want?

**Comment by wobkenh** [comment]
> Gender should be medical gender -> remove "diverse"

Das ist ein gefährliches Pflaster ;)
Ein Dozent bei uns an der Uni erzählte immer davon, wie sie beim Krebsregister 7 Geschlechter unterschieden haben.

>  I'm quite optimistical we can keep it that way by using a regular expression to split the combined control's input value into street and house number component, but is that what we want?

nö. Was wir wollen sind zwei getrennte Felder in einer Zeile, das Hausnummernfeld entsprechend kleiner als das Straßenfeld

> reduce whitespace usage to reduce scrolling as much as possible

Dabei bitte beachten, dass die Stammdatenkomponente auch zur internen Patientenregistrierung und zum Bearbeiten von Stammdaten genutzt wird (d.h. wenn da was geändert wird, dann bitte auch ausprobieren, ob das da noch gut aussieht)

**Comment by jabrandes** [comment]
> Gender should be medical gender -> remove "diverse"

Da wäre ich auch vorsichtig. Ich möchte nicht ausschließen, dass es nicht auch Fälle mit unbestimmten Geschlecht geben könnte. In so einem Fall besser die Option 'divers' behalten und im Label auf das medizinische Geschlecht hinweisen.


> nö. Was wir wollen sind zwei getrennte Felder in einer Zeile, das Hausnummernfeld entsprechend kleiner als das Straßenfeld

Ich habe die Beschreibung zum Adressfeld so verstanden, dass sowohl Straße, als auch Hausnummer in einem Textfeld erfasst werden sollen. @wobkenh, ist das mit den getrennten Feldern in einer Zeile auch das was @jonathangpk meinte?

**Comment by wobkenh** [comment]
Letztendlich ist es aktuell so ziemlich egal, ob wir Straße und Hausnummer einzeln oder getrennt erfassen, solange das nicht Gegenstand unserer Auswertung wird. Sollten wir dagegen für einen speziellen Ort eine Auswertung machen wollen (z.B. Kartenansicht des Ortes und die Straßen werden nach Infektionsanzahl farblich rot, gelb oder grün markiert), so wäre das nicht mehr möglich, wenn Straße und Hausnummer zusammen erfasst werden.
