### ISSUE TITLE
Patient registrieren: Der Patient konnte nicht registriert werden

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#229]
Wenn man unter imis-prototyp.de/app/register-patient versucht einen Patienten zu registrieren kommt die Fehlermeldung:

Patient nicht registriert.
Der Patient konnte nicht registriert werden.

**Comment by jabrandes** [comment]
Ich habe gerade testweise mal eine Patientenregistrierung mit Ramschdaten auf https://staging.imis-prototyp.de/app/register-patient durchgeführt und das scheint laut Feedback und der Patientenliste auch zu funktionieren. @JonasCir, könntest du in dem Zusammenhang noch einige weitere Informationen ergänzen unter welchen Bedingungen und mit welchem Account der Fehler bei dir auftrat?

**Comment by JonasCir** [comment]
@jabrandes Hat dann wohl an der kaputten Datenbank auf staging zu tun gehabt :)
