### ISSUE TITLE
Authentifizierung

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#23]
Authentifizierung (und Verteilung der Zugangsdaten)

**Comment by jojo19893** [comment]
präferiert mit JWT o.ä. hab ich erfahrung mit just hit me :)

**Comment by MichaelSp** [comment]
hier auch: https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.2.RELEASE/reference/html/#cloud-identity-aware-proxy-iap-authentication ?

**Comment by t0bska** [comment]
Closed in favor of #38
