### ISSUE TITLE
Anmeldung auf Staging nicht möglich

### ISSUE THREAD

**Issue by TheJKM** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#230]
Beim Versuch, sich auf Staging anzumelden, passiert optisch für den Nutzer gar nichts. Im Hintergrund geht die Authentifizierung schief, der Server wirft einen 500 für https://staging.imis-prototyp.de/api/auth.

Das Issue tritt mit allen Demoaccounts auf.

**Comment by TheJKM** [comment]
<img width="1792" alt="Screenshot 2020-04-23 at 22 45 34" src="https://user-images.githubusercontent.com/21987613/80147703-318aaa00-85b4-11ea-8a67-55088bde93d9.png">

**Comment by wobkenh** [comment]
Der scheint Vorname/Nachname beim User in der DB nicht angelegt zu haben.
![image](https://user-images.githubusercontent.com/39462297/80154694-6ac91700-85c0-11ea-8f27-5d10efcb5887.png)

**Comment by wobkenh** [comment]
Ich trigger mal einen rebuild, da baut er normalerweise die DB neu auf

**Comment by wobkenh** [comment]
Ich gebs auf, das ist alleine unmöglich :joy: 
Ich kann keinen PR durchmergen, ich kann nicht auf DEV comitten, ich kann nicht in die DB schauen, da ich nicht weiß, wie ich an das PW komme, da es in der Oberfläche keine Möglichkeit dazu gibt. Es gibt auch keine Möglichkeit, den Pod neu zu starten. Über kubectl (wo das eigentlich gehen müsste.?) komme ich nicht rein, da ich nur einen Ladescreen "Ihre Google Cloud Shell-Maschine wird bereitgestellt" bekomme - weiter kommt er nicht.

Entweder später gibt jemand meinen PR frei und DEV wird neu gebuildet, jemand startet den Pod für Staging neu oder jemand, der auf die DB schauen kann, findet heraus, warum firstName und lastName in Staging an der DB fehlen, aber beim lokalen Starten des Services korrekt angelegt werden.

**Comment by MichaelSp** [comment]
Restart hat geholfen
