### ISSUE TITLE
Kontaktpersonen

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#232]
- [x] Ein Patient kann Indexpatient sein
- [x] Ein Patient kann eine (infizierte) Kontaktperson eines (oder mehrerer) Indexpatienten sein

- #301 Zu jeder Person kann eine Kontaktperson hinzugefügt werden. Hier werden nur persönliche Daten und Informationen für den Kontakt abgefragt: Name, Vorname, Geb., Geschlecht, Adresse, Telefon, E-Mail, Derzeitiger Aufenthaltsort, weitere sinnvolle pers. Daten, Art des Kontakts (Haushaltskontakt, beruflicher Kontakt, Kontakt in Gemeinschaftseinrichtung, sonstiger Kontakt), Datum des Kontakts, Beschreibung aka Freitext)

- [x] Patientendetails: Kontaktpersonen auflisten. Für jede Kontaktperson anzeigen, ob  diese Infiziert oder in Quarantäne ist

- #302 Option, beim anordnen von Quarantäne für den Patienten, Quarantäne auch für Alle Kontaktpersonen anzuordnen.

- #303 Auswertung: Wie viele Kontaktpersonen infiziert ein Fall durchschnittlich (sofern Kontaktpersonen erfasst) Diese effektive Reproduktionszahl in Dashboard/Landing Page anzeigen

**Comment by jabrandes** [comment]
Zur Umsetzung der Kontaktpersonen: Ich hatte mir im Rahmen des Database Rework Issue (#181) mal Gedanken gemacht, ob man die üblichen Personendaten (Name, Geschlecht, Geburtsdatum, ...) in eine Oberklasse `Person` packt und `Patient` als eine Spezialisierung/Rolle auffasst. Mit dem Modell könnte man dann alle Kontaktpersonen erstmal als `Person` erfassen (die widerum selbst dem System schon als Patient bekannt sein können), wobei Indexpatient und Kontaktperson über ein zusätzliches Objekt (`ContagiousContact`) mit den näheren Informationen zu den Kontaktumständen (Art, Datum, Beschreibung) verknüpft sind.

Soll ich mal den Ansatz verfolgen und testweise implementieren?

**Comment by JonasCir** [comment]
Hört sich für mich prinzipiell gut an, ich bin aber nicht in der Entwicklung drin. @t0bska @jojo19893 @MariusGiebenhain was denkt ihr?

**Comment by jonathangpk** [comment]
Ich denke Person ~= Patient. Es gibt eigentlich keine großen unterschied ein patient muss auch nicht unbedingt krank sein. Man könnte vlt einen Krankheitsverlauf / Verdachstverlauf dem Patienten/ der Person hinzufuegen für eine Unterscheidung.

**Comment by Jochen-Sch** [comment]
Please check issues 264, 265 and 266 for details on backend and UI

Anmerkung in Bezug auf Person vs Patient: Aktuell reflektiert unsere Patienten Entität in der Tat eine Person und einen Fall gleichzeitig. Diese beides Aspekte wäre später ggf. zu trennen sodass eine Person im Laufe der Zeit von mehreren Infektionen betroffen sein kann . Die Bezeichnung Person vs Patient ist dabei eher nebensächlich d.h. Patient könnte dann in Person umbenannt werden um klarzustellen das diese die Entität der natürlichen Person ist.
