### ISSUE TITLE
Übersichtlichere Ausgaben kritischer Fehler beim Frontend Linting

### ISSUE THREAD

**Issue by jabrandes** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#236]
Während der Entwicklung stand ich bisher immer wieder vor dem Problem, dass der Linter meine Codeänderungen im Frontend nicht angenommen hat und ich die notwendigerweise zu korrigierenden Fehlerstellen suchen musste. Problematisch ist dabei nur, dass sich mittlerweile viele Warnungen angestaut haben, unter denen die Meldungen der kritischen Fehler erst gefunden werden müssen. 

Ich möchte daher anregen, die Konfiguration des Linters soweit möglich für eine übersichtlichere Ausgabe zu überarbeiten. Ich bin mir sicher, dass die Frontendentwicklung beispielsweise von einer Bündelung der kritischen Fehler zum Schluss der Auflistung oder von farblichen Hervorhebungen profitieren würde. Inwiefern soetwas umsetzbar ist müsste allerdings noch geprüft werden.

**Comment by jonathangpk** [comment]
Hast du eine beispiel?

Mit linting meinst du eslint oder? Wenn du den editor richtig einstellst sollte eigentlich alles passen, die `.editorconfig` sollte passen. Ansonsten klappt `yarn lint --fix`eigentlich immer um alles zu beheben. Manuelle suche bracht man eigentlich nicht.

> kritisches fehler anders darstellen
Was genau meinst du? Wenn sich der linter beschwert oder es TS fehler gibt kann er nicht builden. Die warnings sollten überwiegend `unused imports` oder `any` nutzung sein.

**Comment by jonathangpk** [comment]
Und tslint und eslint erros sind doch rot oder?

**Comment by jabrandes** [comment]
Zum Background: Bisher hatte ich den `gradle bootRun` Befehl immer in einem Terminalprogramm ausgeführt. Dieses unterstützt auch Farben und der Gradle-Progress wird auch farblich dargestellt. Die Linter-Ausgaben dagegen werden **nicht** farblich dargestellt. Ich habe testweise auch mal das `--color` Flag beim Aufruf von `vue-service-cli` in der `package.json` ergänzt. Dann funktioniert das mit der Farbe.

Ich habe jetzt gerade leider keinen Screenshot dazu parat, aber kritische Fehler (`error` Fehler) werden scheinbar je nach zeitlichem Auftreten in die Ausgabe reingeschrieben, wodurch ein Linter-Log so aussehen kann:

```
warning ...
warning ...
warning ...
...
warning ...
error ...
warning ...
...
warning
warning

1 error, 70 warnings
```

Das der Build bei kritischen Fehlern abbricht ist soweit klar und erwartet. Das große Manko ist halt die ein, zwei Stellen von den notwendigerweise zu behebenden `error` Ausgaben in dem Meer aus `warning`s zu finden, insbesondere ohne farbliche Kennzeichnung.

**Comment by jonathangpk** [comment]
Ah, ich starte den client immer mit `yarn serve` vlt ist der output da unterschiedlich.

aber gut wenns mit dem color flag klappt :)

**Comment by jonathangpk** [comment]
![image](https://user-images.githubusercontent.com/33756680/80289511-1d26e880-873f-11ea-9907-aa9825fb2bfd.png)

So sehen die warnings bei mir aus, ich denk das meinst du. Aber die Errors sollten unten in rot kommen.

Langfristig können wir die warnings alle beheben, leider bietet ant design teilweise einfach schlecht types an. `form` ist bspw. `any`

**Comment by jabrandes** [comment]
Wir denken gerade scheinbar an verschiedene Linter :see_no_evil:. Der auf den ich mich beziehe (welcher auch immer das ist) ist der vom Gradle `:client:lint` Target. Und der gibt bei mir seine Warnungen und Fehler so aus:

![grafik](https://user-images.githubusercontent.com/16663164/80289723-c5897c80-8740-11ea-9a37-870247bdfbcf.png)

**Comment by jonathangpk** [comment]
oh ok, ja gut der output ist nervig 😁

**Comment by jonathangpk** [comment]
Mit `yarn serve` siehts besser aus ;)

Die anys wegzubekommen ist schon aufwendig, langfristig aber sinnvoll denk ich. Ich wuerde das das ticket aber erstmal schliessen :)
