### ISSUE TITLE
Quarantäne anordnen/requestQuarantine

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#238]
Quarantäne wird nicht direkt vom Gesundheitsamt angeordnet sondern von den zuständigen Ortspolizeibehörden. Heute müssen Anordnungen vom GA von Hand in Listen übertragen werden.
- [x] Neues PatientEvent QurantineRequested: Damit wird ausgedrückt, dass das GA plant die Ortspolizeibehörde darüber zu informieren, damit der Patient eine Quarantäne Anordnung bekommt.
- [x] Die Patient-Detailsübersicht benötigt eine Checkbox (o.ä.) damit der Patient  in den Status QurantineRequested geschickt werden kann
- [x] app/send-to-quarantine anpassen: Für jede PLZ in der gerade eine Person mit Status QurantineRequested enthalten ist: Auflisten aller dieser Personen in dieser PLZ
- [x] Bulk operation um alle QurantineRequested Personen pro PLZ in den Status QurantineMandated zu überführen. Diese Operation soll erstmal eine CSV der From date_plz.csv zurückgeben

**Comment by jonathangpk** [comment]
Muss das schon bis Dienstag fertig sein?

Ich bin der Meinung das wir jetzt nicht die ganze zeit neue feature reinbauen bevor wir unser daten model verändert haben. Das ist sonst doppelt und dreifach die arbeit.

**Comment by Seal33** [comment]
> 
> 
> Muss das schon bis Dienstag fertig sein?
> 
> Ich bin der Meinung das wir jetzt nicht die ganze zeit neue feature reinbauen bevor wir unser daten model verändert haben. Das ist sonst doppelt und dreifach die arbeit.

Stimme ich zu. Das GA hat sich zwar explizit gewünscht, dass das Anordnen von Quarantäne und die benötigte Weiterleitung an die Polizei automatisiert werden sollte. Die sollen aber am Dienstag nochmal sagen wie wichtig ihnen das konkret für die Simulation ist, da wir dann ggf mehr Zeit benötigen (ich schätze das recht aufwändig ein)

**Comment by JonasCir** [comment]
Ich hab das Datum von dem Milestone mal angepasst :)

Absolut richtig, erst schauen, dass alles andere ordentlich läuft und dann die restlichen Features bauen. Ich will auf keinen Fall, dass wichtige Aufräumarbeiten liegen bleiben :smile:

**Comment by wobkenh** [comment]
Ist in Staging. Bitte prüfen

**Comment by JonasCir** [comment]
@wobkenh 
Wenn ich in staging in der Patienten Übersicht im Action Menü Quarantäne vormerken auswähle passiert nichts

Dann steht da Es wurden 0 Patienten für eine Quarantäne vorgemerkt.

**Comment by JonasCir** [comment]
Ansonsten hab ich es ausprobiert und bin sehr zufrieden damit :) 
Polishing würde ich in separaten issues betreiben :)

**Comment by JonasCir** [comment]
Perfekt!
