### ISSUE TITLE
Patientenansicht: ActionMenü für Quarantäne anordnen, testanordnung usw.

### ISSUE THREAD

**Issue by Seal33** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#240]
In der Patientenansicht sollte ein übersichtliches ActionMenü sein. Darüber kann man dann Quarantäne anordnen/anfragen, test anordnen usw (-> hier sollen in zukunft unkompliziert weitere aktionen hinzugefügt werden)

Verwandt mit #238

**Comment by jonathangpk** [comment]
Ich habe auf dem `feature/patient-actions` schon angefangen
Kann gerne jmd weiter machen.

Die Frage wie man den Dialog macht wenn man auf eine Aktion klickt. Entweder man navigiert auf die jeweilige seite oder man hat eine Dialog Overlay. Ich perönlich finde ein Dialog Overlay besser. Man müsste dafür die jeweiligen Componenten aus den vorhanden seiten extrahieren und in einen component packen.

https://github.com/ImisDevelopers/1_011_a_infektionsfall_uebermittellung/tree/feature/patient-actions

**Comment by JonasCir** [comment]
Done
