### ISSUE TITLE
app/patient-list: Access denied

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#242]
403: GET https://staging.imis-prototyp.de/api/auth/institution
403: GET https://staging.imis-prototyp.de/api/auth/user
403: GET https://staging.imis-prototyp.de/api/patients/query-simple/count?query=
403: POST https://staging.imis-prototyp.de/api/patients/query-simple

CC: #239

**Comment by jonathangpk** [comment]
Als welcher nutzer warst du eingelogged?
Bei mir klappen alle requests fuer alle demo nutzer

**Comment by jojo19893** [comment]
jep bitte einmal kurze infos was nicht funktioniert :)

**Comment by JonasCir** [comment]
Gesundheitsamt

**Comment by JonasCir** [comment]
Ok cannot reproduce
