### ISSUE TITLE
Remove Autocomplete within UI Patient Capture

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#245]
Autocomplete may crash browser and break application functionality if values not found

Steps to reproduce (tested on Firefox on Staging)
Enter ZIP code 12345 and press tab
If you type slow it might not allow you to even type more than 2 digits.
Browser stalls and increases memory to several GB within short time of script is not stopped.
If script is stopped application will not work (no drop-down lists and no save)

**Comment by wobkenh** [comment]
PR ist offen. Es fehlte nur ein if :)
