### ISSUE TITLE
Pilot Deployment broken

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#246]
https://pilot.imis-prototyp.de/app/patient-list

Error forbidden when accessing patient list
Hint: This issue does not occur on staging

**Comment by wobkenh** [comment]
Im pilot branch fehlt an den Endpunkten zum Abfragen der Patienten die Rolle 'DEPARTMENT_OF_HEALTH'. In Dev ist genau das schon gefixed worden.

Pilot ist ~50 commits hinter dev. Soll ich einmal dev in den Piloten mergen?

**Comment by JonasCir** [comment]
@wobkenh ja mach das

**Comment by JonasCir** [comment]
Ich würde bei dem Testlauf mit pilot nicht benötigte features einfach aus dem Frontend raus patchen
