### ISSUE TITLE
Data Model/API - Test - Sample Type

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#247]
For a test the sample type must be captured in addition to the test type
Therefore the entity for the test and the according API shall have a new attribute SampleType 
Sample type is a domain with values 'Rachenabstrich', 'Nasenabstrich', 'Vollblut'
When querying test details the according attribute shall also be included

**Comment by wobkenh** [comment]
ist in dev
