### ISSUE TITLE
Data Model/API - Patient Data - Address Fields/Nationality

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#248]
check whether Nationality is correctly captured through API and stored (or if that's a Frontend issue - i.e. not passed) if mising in API and/or DB model please add
make 'houseNumber' optional so that we can include the house number within the street attribute - background: increase data entry speed and alolow complex adresses with Street + HouseNumber + Appartment/Block...
make 'stayHouseNumber' optional so that we can include the house number within the street attribute - background: same as above

**Comment by wobkenh** [comment]
PR ist offen

**Comment by wobkenh** [comment]
in dev
