### ISSUE TITLE
Data Model - Patient Data - Infection Source

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#249]
We need to capture infection sources for a patient:

Add sourceOfInfectionPatient as reference to Patient and sourceOfInfectionDate as date/time and a recordStatus (active/inactive) as bolean (true = default => active) (if this could be a list in the backend for later it would be ideal but single entry is ok for now)
all 3 fields are non-mandatory and should be passed from patient capture and returned for 'patient details'

See also Generic Infection Source: #304

**Comment by wobkenh** [comment]
@jabrandes 
Das hier wird mit deinem Draft #268 gefixed, oder?

**Comment by jabrandes** [comment]
Ja, dieses Issue dürfte da mit drunter fallen. Beim bisherigen Stand von dem Pull Request fehlen entsprechende Features aber noch.

**Comment by JonasCir** [comment]
@jabrandes @Jochen-Sch 
Kann das geschlossen werden?

**Comment by jabrandes** [comment]
Es fehlt noch die Möglichkeit, arbiträre Infektionsquellen anzugeben. Allerdings wäre ich dafür, die ganzen separaten Issues zu Kontaktpersonen und Infektionsquellen mal bezüglich der noch fehlenden Features zu mergen. Ich habe bei den 3 bis 4 related Issues ein wenig den Überblick verloren was jetzt genau noch zu erledigen ist. Im Pull Request #268 hatte ich mal aufgelistet welche Features der verschiedenen Issues noch fehlen dürften.

**Comment by Jochen-Sch** [comment]
Gute Idee ... sollten wir im Rahmen des Status huete machen ... dann können wir die alten Issues schliessen und 1-2 konsolidierte Issue für das Thema Kontakte machen

**Comment by JonasCir** [comment]
Ja finde ich auch eine gute Idee! @LeonardKoll sieht das denke ich ähnlich  :)

**Comment by btobi** [comment]
Remaining task moved to #304
