### ISSUE TITLE
Frontend Application - Initial Screen

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#250]
The initial screen after logon should not be the account management - especially as this is not yet adjusted role-based
The proposal is to load an initial page that contains
>>
Willkommen in IMIS
[LOGO]
Infektionsmelde- und Informationsystem

Sie sind für die Institution <Insitutionsname> angemeldet

Wählen sie im Menü auf der linken Seite den Bereich aus den sie bearbeiten möchten.
<<
All text centered

**Comment by wobkenh** [comment]
In #237 (PR #244) wurde ein einfaches Dashboard implementiert. Ist in dev. Auf dem Dashboard werden unbearbeitete Fälle angezeigt. Kann das Issue hier geschlossen werden?

**Comment by Jochen-Sch** [comment]
Was heisst unbearbeitet ... bzgl. welchem Taks des GA? Der Screen ('Dashboard') ist aus meiner Sicht weder ein Dashboard noch ist klar was es darstellt (Spezifikation fehlt komplett)

**Comment by wobkenh** [comment]
Okay, was machen wir jetzt?
Dashboard näher spezifizieren und anpassen oder das jetztige Dashboard austauschen durch das "Willkommen in IMIS" Dashboard aus diesem Ticket?

**Comment by JonasCir** [comment]
Ich bin für Dashboard lassen und etwas anpassen

**Comment by Jochen-Sch** [comment]
Da offensichtlich niemand bereit ist ein'Dashboard' zu spezifizieren, sollten wir es durch die Startseite ersetzen. Um Zeit zu sparen können man die login-abhängige Meldung mit der Institution auch weg lassen sodass ses nur noch ein statischer Screen ist
