### ISSUE TITLE
Frontend Application - General Controls

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#251]
remove search on top of application
move application 'Account' to before 'Logout'
rename application 'Account' to 'Benutzerkonto'
rename action 'Logout' to 'Abmelden'

**Comment by wobkenh** [comment]
Ich habe Logout und Benutzerkonto jetzt nach oben rechts in die Navbar geschoben, da es in den meisten anderen Services (Amazon, Facebook usw.) auch so ist.

**Comment by wobkenh** [comment]
in dev
