### ISSUE TITLE
UI "Patient Registrieren" - Screen Labels & Field alignments

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#253]
UI "Patient Registrieren" - Screen Labels & Field alignments
change text 'Registrieren Sie hier neue Patienten in IMIS. Bitte füllen Sie den Bogen vollständig aus. ' -> 'Registrieren Sie hier neue Patienten in IMIS. Bitte erfassen Sie die nachfolgenden Daten so vollständig wie möglich. Oflichtangaben sind mit "*" markiert'
within section 'Allgemeines' change text 'Adresse' -> 'Wohnort'
within section 'Allgemeines' change text 'Kontakt und Sonstiges:' -> 'Kommunikation und Sonstiges'
change label 'Allgemeines' -> 'Personendaten'
deactivate ZIP code autocomplete as it draws dramatically memory if not found and crashes browser
Set default country to 'Deutschland'
Make additional entry field for 'Beruf' (below drop-down list) optional (if drop-down value 'keiner der genannten ...' is selected a user may enetr the job but does not need to)
within section 'Symptoms' change text 'Welche Symptome weist der Patient auf?:' -> 'Welche Symptome weist der Patient/die Patientin auf?
within section 'Symptoms' change text 'Hat der Patient für diese Saison eine Influenza-Impfung erhalten?:' -> 'Hat der Patient/die Patientin für diese Saison eine Influenza-Impfung erhalten?'
within section 'Symptome' remove 'Beatmungspflichtige Atemwegserkrankung' and 'Akutes schweres Atemsyndrom (ARDS)' as these are no symptoms but illnesses
change section title 'Vorerkrankungen' -> 'Riskikofaktoren' (alternatively: 'Vorerkrankungen und Risikofaktoren'
within sections Vorerkrankungen' change text 'Welche Vererkrankungen und Risikofaktoren liegen vor?:' -> 'Welche Vorerkrankungen und Risikofaktoren liegen vor?'
within all sections: check if there is a  question with "?" and if there is an additional ":" remove the ":"
change section title 'Krankheit' -> 'Krankheit und Zustand'
within section 'Krankheit' move 'Art der Erkrankung' and 'Erkrankungsdatum' to first line within section
within section 'Krankheit' move 'Meldedatum as 3rd column in the first line within section
change fixed value within 'Art der Erkrankung' to COVID-19
move field 'Fallstatus' to next column in line with 'Art der Erkrankung'
remove fields 'Wurde eine Erregerdiagnostik beauftragt', 'Labor' and 'Datum der Probenentnahme' (this data is derived from tests)

check and correct all field tab index values so that navigation with tab is according to logical field sequence on the screen

reduce spacing between lines so that more data fits on the screen [apporx 50% of current should be fine] (at least reduce white spacing sub-sections like 'Adresse' ...)

**Comment by wobkenh** [comment]
Die meisten Punkte habe ich erledigt.
Aber:
- Der PLZ Bug wurde in #245 gefixed.
- Beruf ist schon optional. Soll der Text im Dropdown geändert werden?
- der Patient / die Patientin wird bereits dynamisch unterschieden, abhängig davon, was bei Geschlecht angegeben wurde
- Ich weiß nicht, ob ich die Neuanordnung unter "Krankheit" richtig verstanden habe.
- Bzgl Tab Order: Die DateInputs zicken leider ziemlich rum. Da sollten wir darüber nachdenken, ob bei z.B. Geburtsdatum nicht ein normales Inputfeld mit entsprechender Validierung ausreicht.

**Comment by Jochen-Sch** [comment]
Beruf optional - aber noch nicht auf staging, oder?
Text in Drop-Down kann man ändern wobei es ja nicht verpflichtend sein sonn - ok aus meiner Sicht
Einige wollten unbedingt divers beibehalten - daher macht eine Textänderung nach Geschlecht keinen Sinn ... es müssen also sowieso mind. bei divers beide gezeigt werden ... der Aufwand das dynamisch zu ändern auch also wenig Sinn (zumal es später bei einer Übersetzung schwierig würde)

Bzgl. "Krankheit":
Ergebnis wäre 1 Zeile (3 Spalten) Krankheit / Erkrankungsdatum / Meldedatum

**Comment by wobkenh** [comment]
oh, stimmt, Beruf war noch required - muss mich gestern versehen haben.

Bei Krankheit habe ich jetzt Krankheit und Status in eine Zeile und Erkrankungs und Meldedatum in die nächste, da Status ansonsten so alleine steht.
