### ISSUE TITLE
UI "Patient Registrieren" - Infection Source

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#255]
within section 'Exposition' add a possibility to enter 'Quelle der Infektion (falls bekannt)' with the following 3 fields:
 1. a possibility to seach for an existing patient based on name etc (regular patient identify) andstore the reference to that patient if selected ... labeled as 'bekannter Kontakt'
 2. a possibility to enter any person information, location information or event information as string ... labeled as 'Daten zur Infektionsquelle'
 3. a date of exposition labeled as 'Letztes Kontakt-Datum'

**Comment by wobkenh** [comment]
Umsetzung erfolgt entweder noch in #268 oder danach in einem separaten Branch

**Comment by JonasCir** [comment]
@Jochen-Sch @wobkenh 
Kann das geschlossen werden

**Comment by Jochen-Sch** [comment]
@JonasCir Nein, oder hast du die beschriebenen Felder auf Staging oder Pilot schon gesehen?

**Comment by JonasCir** [comment]
My bad :) War zu sehr auf die Infektionsquelle im Titel fokussiert

**Comment by btobi** [comment]
Moved to #301
