### ISSUE TITLE
UI "Probe Zuordnen" - Screen Labels & Interaction & Proben-Material

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#256]
add field 'Proben-Material' as Value List with allowed value 'Rachenabstrich', 'Nasenabstrich', 'Vollblut' (align with issue for backend service)
hide button 'Speichern' for confirmation of save activity (confirmation dialog)
add button 'Nächste Probe' on confirmation dialog to clear confirmation message and activate entry fields
remove icons for "Testtyp" value options as they are not meaingful

**Comment by wobkenh** [comment]
> hide button 'Speichern' for confirmation of save activity (confirmation dialog)

Ich verstehe den Satz nicht. Wenn ich den Speichern-Button verstecke, wie soll dann ein Bestätigungs-Dialog geöffnet werden?

> add button 'Nächste Probe' on confirmation dialog to clear confirmation message and activate entry fields

Ist die jetztige Variante nicht schneller? Man gibt alles ein, drückt auf speichern und kann sofort die nächste Probe eingeben.

Ich kann einen Dialog "Wollen Sie wirklich speichern?" gerne einbauen, hätte dafür aber gerne die Bestätigung, dass das wirklich so gemeint war.

**Comment by Jochen-Sch** [comment]
Hallo Henning, 
das Problem ist dass der Dialog in der Form für den User unlogisch ist.
Es erfolgt eine Bestätigung dass die probe zugeordnet ist, die mit einem aktivierten Speichern button. Dies führt dazu dass die logische Abfolge wäre die Zuordnung nun zu speichern. Wenn der User einfach die nächste Probe zuordnet steht unten nach wie vor die Bestätigung der letzten Probe. Je nach Aufstellung des Monitors (d.h. der nächste Patient sieht den Screen bei der Probenahme) könnte das sogar ein Datenschutzproblem sein, weil sowohl Patienten ID als auch Probe ID sensitive Daten sind.

**Comment by Jochen-Sch** [comment]
Darüber hinaus geht es auch später um eine ggf. Wiederverwendung des Screens im Kontext der vollständigen Erfassung bei der direkt anschliessend das Ergebnis im GA erfasst wird.

**Comment by wobkenh** [comment]
Habe den Dialog jetzt eingebaut. Bitte in staging prüfen, ob ich das jetzt richtig verstanden habe.

**Comment by Jochen-Sch** [comment]
Passt aus meiner Sicht. Super.
