### ISSUE TITLE
UI "Testresultat Zuordnen" - Screen Labels & Interaction & Result Options

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#257]
for 'Testresultat' remove all value options except 'Test positiv' and 'Test negativ' (this change is only for 'Simulation')
hide button 'Speichern' for confirmation of save activity (confirmation dialog)
add button 'Nächstes Ergebnis' on confirmation dialog to clear confirmation message and activate entry fields

**Comment by wobkenh** [comment]
Gleiche Frage wie bei #256

**Comment by Jochen-Sch** [comment]
Please check description. Solution still contains obsolete Results that can be selected.

**Comment by wobkenh** [comment]
Stimmt, habe ich übersehen. Habe ich angepasst.
