### ISSUE TITLE
UI "Alle Patienten" -  Patient List UI Changes

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#258]
The goal of this issue is to make the patient overview list more compact.

- [x] Change icon for detail link to something other than search and also not used for other things than detail view throughout our application
- [x] Combine 'Nachname' and 'Vorname' to a combined value <Nachname>, <Vorname>
- [x] Combine Zip code and town
- [x] Remove email address column
- [x] Add 'Alter' to list (calculated within UI based on date of birth for Simulation)
- [x] Add 'Index-Patient' to List (align with backend data model extension to store source of infection patient if filled)

**Comment by wobkenh** [comment]
Beim Icon war ich mir jetzt nicht so sicher.
Falls das Icon noch nicht gefällt, hier sind alle verfügbaren Icons:
https://www.antdv.com/components/icon/#Icon

Bei den Indexpatienten kann es nach Datenmodell mehrere geben. Soll ich dann auch alle anzeigen? Aktuell zeige ich nur die erste eingetragene Person an.

**Comment by jabrandes** [comment]
Sehe ich das richtig, dass dieses Issue geschlossen werden kann?

**Comment by btobi** [comment]
Wird automatisch geschlossen, sobald in master gemerged :)
