### ISSUE TITLE
UI 'Patienten Details' -  UI Changes (Falldaten)

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#259]
Change Tab title 'Stammdaten' to 'Falldaten'
Change button 'Stammdaten editieren' to 'Daten ändern'
Combine 'Vorname' 'Nachname' into one line as 'Nachname, Vorname': <Nachname>, <Vorname>
Put 'Geschlecht' into the same line (2nd column) with 'Geburtsdatum'
Remove 'Hausnummer' (in alignment withdata model cchanges to include 'houseNumber' in Street
Combine 'PLZ' and 'Ort' to a combined value <PLZ> <Ort>
move 'Status' to before 'Vorerkrankungen' as it indicates the actual start of case data
rename 'Status' to 'Fall-Status'
Add field for dateOfIllness ('Erkrankungsdatum' to the same line as 'Fall-Status' - 2nd column)
Add field for dateOfReport ('Meldedatum' to the same line as 'Fall-Status' - 3rd column)

Add last date for change of test to attributes of test listwith label 'Aktualisiert' (before 'Kommentar')

**Comment by wobkenh** [comment]
ist in dev
