### ISSUE TITLE
Data Model/API - Patient Contacts

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#264]
A new entity for capturing contacts in relation to a index patient is required.
The following attributes shall be stored in relation to a patient
Either a patient link (reference to a different existing patient) or the set of lastName firstName street, zip, city, telephone, comment
Each patient may have multiple contacts (1:n)

An API shall allow to create such entries (bulk) and subsequently create a new patient entry with case status 'Kontaktfall' (may be interpreted status) from any entry that contains last name and first name without a reference to an existing patient
For all entries that have a linked patient a corresponding infection source entry shall be created

An API shall allow to mark entries as inactive. This will trigger the correspjding infection source entry for the contact patient to be inactive too.

**Comment by jabrandes** [comment]
Some questions regarding the topic:

1. What exactly is meant by 'bulk'? Does it mean that a single REST endpoint should accept a list of contacts to create, while each individual such entry is either referencing an existing `Patient` entry or defining a new one?
2. What is meant by inactive entries?

**Comment by Jochen-Sch** [comment]
Hi, sorry yes. the description is not detailed enough. 
1.
Bulk means that the frontend could send a list of entries where each entry could contain either 
a linked patient (reference to an existing patient) + date and comment  
or 
the following attrribtes: last name, fisrt name, street, zip code, city, date and comment
... while not all of these attributes are mandatory as some might not be provided by the index patient
In case the contact is not a linked patient a new patient record should be created. Therefore the contact entity does only need to store the attributes patient reference, date and comment

2.
Such a contact entry could be identified as irrelevant later on. As medical system cannot just delete data the functionality would need to mark an entry as inactive (just a flag either active default = true or vice versa). This could also be implemented later as it's not relevant for simulation.

3. Yes infection source is the additional attribute set fro the source of infection in the patientrecord (#249). A newly created patient record out of a contact list should hold the index patient as infection source.

**Comment by jabrandes** [comment]
Thank you for the clarification. I'm still not sure how the best approach to 2. and 3. would look like, but I do have an idea regarding bulk import of contact patients for an already existing source patient that would allow to use both existing `Patient` identifiers, as well as patient definitions based on the `CreatePatientDTO`. One could use a custom Jackson `Converter` class that would map the contact field to either an ID-String or a `CreatePatientDTO`, depending on whether the field contains a string or an object.
