### ISSUE TITLE
UI 'Patienten Details' -  UI Changes (Infektionskette) Display

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#265]
UI 'Patienten Details' -  UI Changes (Infektionskette) Display

A new tab is inserted after tab 'Falldaten' within the patient detail screen labeled 'Infektionkette'
The tab consists of 2 sections with a list display each.
Height shall be dynamic with a maximum height ofthe first section to be 40% of the screen height but a minimum of 1 data line within the list

Section infection source with title 'Infektionsquellen'
below is a list of infection sources for the patient as captured during patient registration with the following columns:
- a name field 'Name' in the form <Nachname>, <Vorname> in case of a person or <Nachname> if no first name is maintained
- date of last contact 'Kontakt-Datum'
for simulation this will be only 1 entry while later it could be a list 

Section infection contacts with title 'Kontakte'
below is a table with a list of captured contacts displaying the following columns:
- in case of a linked patient record:
  - a name field 'name' in the form <Nachname>, <Vorname> 
  - location field 'Ort' in the form of <ZIP> <City> either based on the contact record

**Comment by btobi** [comment]
According to #268, the only thing missing here is the location / context of contact in the table. I added this in #300.

However, I don't see the implementation of the part with "in case of a filled sourceOfInfectionString". Is this still relevant? @Jochen-Sch @jabrandes

**Comment by jabrandes** [comment]
It is currently not possible to specify arbitrary infection sources. That is a feature that still has to be implemented.

**Comment by btobi** [comment]
Moved to #301
