### ISSUE TITLE
UI 'Patienten Details' -  UI Changes (Infektionskette) Maintenance

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#266]
Infektionsquellen:
within the title line of section 'Infektionsquellen' there is a action button labeled 'Quelle erfassen' (right alinged with the list)
Upon pressing the button a layover dialog appears with a table where new lines can be added and each line contains the following fields:
same fields as for patient capture (infection source -> see issue 255) 
Hint: for simulation scope limitation we would limit this to 1 entry (so the resulting liust would only contain 1 entry)
Within each line of the list display there is a trashcan icon at the end which sets the record as inactive and geys it out (change text color to grey). The action tiggers a flag to set the record as inactive

Kontakte:
within the title line of section 'Kontakte' there is a action button labeled 'Kontakte erfassen' (right alinged with the list)
Upon pressing the button a layover dialog appears with a table where new lines can be added and each line contains the following fields:
'Nachname oder Name' a string field to capture a person last name, location name or event name 
'Vorname' a string field to capture a person first name
'Patient' a link field to allow linking an existing patient (non-editable - filled by UI logic - see below)
'Strasse' a string field to allow capturing the street and house number of the address of the person, location or name in field 1
'PLZ' a string field to allow capturing the city of the address of the person, location or name in field 1 
'Ort' a string field to allow capturing the city of the address of the person, location or name in field 1
'Telefon' a string field to allow capturing a contact phone number
'letzter Kontakt' a date field to maintain a last contact date
'Kommentar' as string field for any additional information provided by the index patient
in case the user entered a last name and first name in fields 1+2 the system will search for matching patients in the system and propose matches as an in-field list (list can also appear in link field)
the in-field list shall display last name, firstnamme, age, zip code and city to allow the user to judge whether this is the same person (potentially by asking additional questions to the index patient or checking theadditionaly provided data)
in case the user selects an entry the name fields will be automatically completed with <Nachname> and <Vorname> and the 'Patient' field will contain the link to the existing patient record
in case the user does not select an entry the remaining data can be filled as available
After completion for 1 or multiple added lines the user can save the data.
Upon saving each line that has a linked patient will create an additional infection source entry for the linked patient (not implemented for simulation)
Upon saving each line that has no linked patient and a first name maintained will create a new patient record with case status 'Kontaktfall' and the entered key data
Upon saving each line that has no linked patient and no first name maintained will create a contact event 'Veranstaltung' (not implemented for simulation)
After saving the layover dialog will close and a confirmation mesage will apear confirming that '<n> neuen Kontaktfälle angelegt' where <n> reflects the number of newly created patient records

Within each line of the list display there is a trashcan icon at the end which sets the record as inactive and geys it out (change text color to grey). The action tiggers a flag to set the record as inactive. The action has no effect on the existance of a created contact patient but sets the respective infection source of the contact patient also to inactive.

Hint:
Possibly a separate backend service (API) is required to save contact patients as not all mandatory fields are filled (alternatively the backend service may allow to have different validation of called with a specific parameter to ommit such validation [only last name and first name and either zip code or city are mandatory). 
This should be aligned iwth the according backend issue

Remark:
As the effort for multiple infection sources or contact events is too big to be completed until simulation these are only indicated by the possibility to capture but will not be saved

**Comment by btobi** [comment]
Moved to #301
