### ISSUE TITLE
Autocomplete vorhandener Patientendaten

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#28]
Wenn eine Person bereits registriert wurde und man bestimmte persönliche Daten eingibt, wird die entsprechende Personen (-ID) automatisch ausgewählt
(leider nicht mit Krankenkassennummer möglich wg. privatversicherten)

Als solche Daten bieten sich an:
Vorname, Nachname, Geburtsdatum, Postleitzahl (z.B. mit der Straße als Sicherheitsfrage)

-> Dadurch können an Teststationen und bei Folgetests die Daten schneller erfasst werden. Ggf. mit QR-Code als alternative ergänzen

**Comment by lordpomeroy** [comment]
Should be done automatically due to ID generation.

**Comment by t0bska** [comment]
Muss in Hinblick auf ein Sicherheitskonzept überdacht werden. Würde das Feature und das dazugehörige Eingabefeld vorschlagen, vorerst zurückzustellen bzw, zu entfernen. Zugriff auf den Patientendatensatz nur mit der ID oder durch das Gesundheitsamt.

**Comment by t0bska** [comment]
Benötigt eigene GUI, wo man einen großen Teil der Person. Daten eingibt, um ID zu bekommen. Erstmal keine Priorität.

**Comment by t0bska** [comment]
Closed because of low relevancy
