### ISSUE TITLE
[Staging] /api/auth errors

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#280]
Staging:
{
"timestamp":"2020-05-06T12:39:27.842+0000",
"status":500,
"error":"Internal Server Error",
"message":"could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet",
"path":"/api/auth"
}

**Comment by wobkenh** [comment]
Eine DB Spalte hat wieder gefehlt.
Ein Neustart hat das Problem behoben. Sehr seltsames Verhalten.
