### ISSUE TITLE
New master release

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#290]
Master is quite old and the landing page does not even mention that we are part of the SE program. As we are getting more and more attention, we should update the master more frequently again :)

**Comment by wobkenh** [comment]
#291 done

**Comment by JonasCir** [comment]
Thanks for merging :) AFAIK you have to make a release to trigger rebuild :+1: I'm not familiar with the details though @MichaelSp

**Comment by MichaelSp** [comment]
it's rolling https://github.com/ImisDevelopers/1_011_a_infektionsfall_uebermittellung/releases/tag/0.3.0
