### ISSUE TITLE
Changing Patient Base Data resulting in Error

### ISSUE THREAD

**Issue by jabrandes** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#292]
When trying to change a patient's base data (e.g. Name), the server generates an error related to `LocalDate` parsing, therefore preventing data update.

![grafik](https://user-images.githubusercontent.com/16663164/81704110-bfe4a400-946d-11ea-8a25-9d7f97f9f3d0.png)

**Comment by jabrandes** [comment]
This is a duplicate of #296.

**Comment by wobkenh** [comment]
Ups, nicht gesehen, dass du schon ein issue erstellt hattest :sweat_smile: 
Sorry!
