### ISSUE TITLE
Invalid Date: Backend liefert Zeitstempel als Object

### ISSUE THREAD

**Issue by wobkenh** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#296]
title.

Grund: Es wurde in einem der letzten Commits ein ObjectMapper definiert. Dieser wurde jedoch in Bezug auf Timestamps/Dates nicht richtig konfiguriert.

**Comment by jabrandes** [comment]
@wobkenh, scheinbar sind wir beide parallel auf dasselbe Problem gestoßen. Dementsprechend hatte ich jetzt auch bei mir einen Pull Request rumliegen, der sich auf das Problem konzentriert (#293) :see_no_evil:. 

Auch wenn dein PR das Problem bereits behebt möchte ich dich dennoch bitten, einmal über #293 rüberzuschauen, da dessen Lösung ohne Überschreiben des Standard-`ObjectMapper` auskommt.

**Comment by jabrandes** [comment]
Da das grundlegende Problem so oder so gefixt ist schließe ich mal dieses Issue.
