### ISSUE TITLE
Quarantäne inklusive Kontaktpersonen vormerken

### ISSUE THREAD

**Issue by btobi** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#302]
**Als User will ich beim Vormerken der Quarantäne für eine Person gleichzeitig auch alle Kontaktpersonen für die Quarantäne vormerken, damit ich nicht die Detailansicht jedes Patienten einzeln aufrufen muss.**

In der Ansicht für Quarantäne vormerken soll hierfür eine zusätzliche Checkbox angezeigt werden (bspw. "Quarantäne auch für alle Kontaktpersonen vormerken").

Kontaktpersonen sind alle Personen, die in der Patienten-Detailansicht unter Infektionskette > Kontaktpersonen aufgelistet sind.

Anmerkung: Bitte auch gleich den ausgewählten Patienten in der "Quarantäne vormerken"-Ansicht mit anzeigen. Aktuell wird der Patientenname nicht angezeigt wenn man aus der Patienten-Detailansicht kommt. Issue dazu: #308

**Comment by LeonardKoll** [comment]
Pull Request für #308 kommt morgen.

**Comment by wobkenh** [comment]
Habs soweit vorbereitet. Wenn der PR für #308 morgen durch ist, kann ich den bei mir rein mergen. Dann muss ich wsl noch eine kleine Anpassung machen und dann sollte das laufen.

**Comment by LeonardKoll** [comment]
PR submitted, du bist reviewer.

**Comment by wobkenh** [comment]
Ist nach dev gemerged. Bitte testen, ob das so ok ist

**Comment by JonasCir** [comment]
@Jochen-Sch @lordpomeroy Könnt ihr testen?
