### ISSUE TITLE
Fehlender Name bei Quarantäne vormerken via Action Menü

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#308]
Steps to reproduce:
1. Alle Patienten Übersicht
2. Person auswählen per Doppelklick
3. Aktionen: Quarantäne vormerken

Der Dialog zur Vormerken enthält nur Datum und Kommentarfeld. Weitere Informationen zum Patienten (wie Name. ID, Geburstag etc) wäre übersichtlicher.

Ähnlich zu #281: @btobi wäre das was für dich? :smile:

**Comment by btobi** [comment]
Ich hab das tatsächlich schon als Anmerkung in #302  hinzugefügt. Ich hab die beiden mal verlinkt.

**Comment by JonasCir** [comment]
Vielen Dank sieht gut aus!

Patienten-ID: Daniel Bauer (DCCA6E6A)  | soll hier noch das Geburtsdatum rein zur eindeutigkeit?

 Bar Foo                               Infektionsstatus unbekannt <- Soll hier noch mehr als der Name hin?
Datum Kontakt: 21.04.2020     Keine Quarantäne

**Comment by LeonardKoll** [comment]
@JonasCir 
Die Anmerkung gehört zu: #302 ( @wobkenh )
