### ISSUE TITLE
Quarantäne - CSV-Export

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#311]
In der exportierten CSV-Datei sollte neben PLZ, Quarantäne bis, Vorname, Nachname und Adresse auch

- [ ]  Der Titel
- [x] Das Geschlecht
- [x] Das Geburtsdatum
- [x] Der Kommentar der Quarantäne-Anordnung
- [x] Der aktuelle Aufenthaltsort
- [x] Außerdem schummelt sich in die Adresse noch ein "null" ein. (Bug)
----
Übertragen von #305 :
Add following information to the csv export:

- [x] Index patient (first and last name)
- [x] Date & Place (#301)
- [x] Context
- [x] Test result

**Comment by btobi** [comment]
Das sollte dann auch in den simulation Milestone, oder nicht? @JonasCir

**Comment by JonasCir** [comment]
Jupp :)

**Comment by LeonardKoll** [comment]
Wir erfassen einen Titel in der Registrierung. Der wird aber nie ans Backend übergeben und dort gibt es auch keine entsprechenden Felder dafür. Oder übersehe ich da was?

**Comment by LeonardKoll** [comment]
"Außerdem schummelt sich in die Adresse noch ein "null" ein. (Bug)" - Das Problem tritt bei mir nicht auf. Gibts dazu mehr Infos? @JonasCir @t0bska 

Der Rest ist erledigt in https://github.com/ImisDevelopers/1_011_a_infektionsfall_uebermittellung/tree/feature/311

**Comment by JonasCir** [comment]
PLZ | Quarantäne bis | Vorname | Nachname | Adresse
-- | -- | -- | -- | --
66893 | 19.05.2020 | Fin | Bauer | Nordtstraße 81 null 66893 Dudweiler

**Comment by JonasCir** [comment]
@LeonardKoll Das null landet in der Adresse
