### ISSUE TITLE
Quickfixes for UI (Simulation focus!)

### ISSUE THREAD

**Issue by lordpomeroy** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#315]
- [x] Remove Copyright (Landingpage and inside the application itself)
- [x] Home Button for public register
- [x] Remove(hide) from Login Page: test_lab, test_doctor, link to "institution creation"
- [x] Remove(hide) menu entry "Alle Tests"
- [x] Add Hint to "Statistiken": "*Statische Testdaten"
- [x] Remove search from "Statistiken" as it is not working
- [x] Remove "Aktionen" for testing_site in Patient Details
- [x] Remove "Aktionen" in Patient Details for all institutions except health_agency
- [x] ~Disable~ Hide Button "Passwort wechseln" from User Account
- ~Change Button "Passwort wechseln" to "Passwort ändern"~
- [x] Disable User Deletion Button in User Account

**Comment by JonasCir** [comment]
This should target the pilot branch right?

**Comment by lordpomeroy** [comment]
Yes, if it is on staging for a short time period that is not hurting, but most of the points will later be re-enabled once they are working correctly.

**Comment by Jochen-Sch** [comment]
additional refinement for Action button added (remove for all non health agency).

**Comment by btobi** [comment]
Fixes last issued added by Jochen.
