### ISSUE TITLE
Apply latest bugfixes of dev branch to pilot

### ISSUE THREAD

**Issue by jabrandes** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#323]
***Author's Note:** I'm asking for verification of this issue*

The `pilot` branch in its current form is lacking bugfixes that have already been applied to the `dev` branch. Since I recall that `pilot` branch is used for simulation and some of those bugfixes are related to errors that result in failure of core functionality, it should be of great importance that those are also patched into the `pilot` branch.

**Comment by LeonardKoll** [comment]
Let's discuss / do this today, 17:15h on Discord.
