### ISSUE TITLE
Fehler beim Hinzufügen des Testergebnis

### ISSUE THREAD

**Issue by philipplott-ship-it** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#325]
**Beschreibung**
Beim Hinzufügen eines Testergebnis als Test-Lab erhalte ich einen Index 0 out of bounds for length 0 Fehlermeldung. Für mich - in der Rolle als Test-Lab ;) - ist mir nicht klar, wo mein Fehler liegt

**Eingeloggt als**
Test-Lab
**Link**
https://imis-prototyp.de/app/submit-test-result

**Browser**
Chrome 
**Screenshot**
![image](https://user-images.githubusercontent.com/65396262/82184420-e9775280-98e7-11ea-8e07-add1c03fe1a4.png)

**Comment by philipplott-ship-it** [comment]
tritt auch auf unter https://staging.imis-prototyp.de

**Comment by lordpomeroy** [comment]
Check if it is an edge case first,

**Comment by LeonardKoll** [comment]
Vermutete Ursache:

- Eingabe einer ungültigen Test-ID (erzeugt exakt diesen Fehler)
- Ähnliche Fehler treten auf wenn die Labor zeile falsch befüllt ist (auch beim anlegen eines Tests)

Weitere gefundene Probleme

- Kommentare sind auf varchar länge limitiert
- Lange Kommentare erzeugen ein Flimmern des Textfelds (zumindest bei mir, Win10, Chrome)

**Comment by LeonardKoll** [comment]
Kommentare sind auf varchar länge limitiert: Verwendung von TEXT cols (@Lob) erfordert die Umstellung von Auto-Commit auf Transaktionen. Das ist eher kein Quickfix.
