### ISSUE TITLE
Land wird bei Patienten-Überblick nicht angezeigt

### ISSUE THREAD

**Issue by philipplott-ship-it** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#330]
**Beschreibung**
Der Eintrag land ist beim Patienten-Überblick leer, obwohl das Feld gefüllt ist.
**Eingeloggt als**
Doctor
**Link**
https://imis-prototyp.de/app/patient/16D9D8FA
**Browser**
Chrome 
**Screenshot**
Der darf gerne auch den Console Log beinhalten (optional)
In Chrome zB unter F12 > Console 
![image](https://user-images.githubusercontent.com/65396262/82185961-555aba80-98ea-11ea-8391-7ac2f546442a.png)

**Comment by Jochen-Sch** [comment]
Please test on the correct landscape : staging.imis-prototyp.de not imis-prototyp.de

**Comment by jabrandes** [comment]
By the looks of it, the error is also present on IMIS Staging.
