### ISSUE TITLE
Arzt kann Patienten nicht in Quarantäne schicken

### ISSUE THREAD

**Issue by philipplott-ship-it** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#331]
**Beschreibung**
Als Arzt, kann ich einen Patienten nicht in Quarantäne schicken. Zusätzlich ist ein Type in der Fehlermeldung "beim hinterlegen" -> "beim Hinterlegen"

**Eingeloggt als**
Doctor 
**Link**
Patient -> https://imis-prototyp.de/app/patient/916B3E13
Screen mit dem Fehler -> https://imis-prototyp.de/app/send-to-quarantine

**Browser**
Chrome
**Screenshot**

![image](https://user-images.githubusercontent.com/65396262/82186228-ce5a1200-98ea-11ea-89f2-be8e35296b07.png)

**Comment by philipplott-ship-it** [comment]
Kann auch sein, dass ich das als Arzt nicht darf? Laut Dokument macht das das Gesundheitsamt. Falls dem so ist, macht es vielleicht Sinn diese Funktion nicht anzuzeigen, wenn man sie nicht durchführen darf

**Comment by philipplott-ship-it** [comment]
![image](https://user-images.githubusercontent.com/65396262/82187515-d31fc580-98ec-11ea-8660-639683c87760.png)
 auf staging ebenfalls

**Comment by Jochen-Sch** [comment]
In der Tat darf das nur das Gesundheitsamt
