### ISSUE TITLE
Unlogische Datenerfassung bei Patientenregistrierung führt nicht zu sichtbaren Fehler

### ISSUE THREAD

**Issue by philipplott-ship-it** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#333]
**Beschreibung**
Man kann Patienten erfassen, die noch nicht geboren sind - aber bereits verstorben sind. Ein Speichern eines solch ungültigen Datensatz führt in der Konsole zu einem Fehler, abgesehen davon passiert aber einfach nichts. 

**Eingeloggt als**
Test-Site 
**Link**
https://staging.imis-prototyp.de/app/register-patient
**Browser**
Chrome 
**Screenshot**

![image](https://user-images.githubusercontent.com/65396262/82189823-542c8c00-98f0-11ea-8c9c-9b1104babad4.png)

![image](https://user-images.githubusercontent.com/65396262/82189499-c8b2fb00-98ef-11ea-9f67-a0369c8b7e7c.png)

**Comment by lordpomeroy** [comment]
Error might be the same as in #345 and #334.

**Comment by JonasCir** [comment]
See above. Error related to #334 . Field validation was added to #52 .
