### ISSUE TITLE
Dateneingabe bei "Patient ist hospitalisiert" nicht möglich

### ISSUE THREAD

**Issue by philipplott-ship-it** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#334]
**Beschreibung**
Eine Dateneingabe für das Feld "Patient ist hospiltaisiert" wird nicht übernommen und führt dann zu einem Fehler
**Eingeloggt als**
Test-Site
**Link**
https://staging.imis-prototyp.de/app/register-patient
**Browser**
Chrome
**Screenshot**
![image](https://user-images.githubusercontent.com/65396262/82189935-8807b180-98f0-11ea-959a-3bfed3d8dc6f.png)

**Comment by btobi** [comment]
#345 Possible duplicate
