### ISSUE TITLE
Buttons verschoben bei "In Quarantäne senden"

### ISSUE THREAD

**Issue by philipplott-ship-it** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#335]
**Beschreibung**
siehe Screenshot
**Eingeloggt als**
DPH (Department of Health)
**Link**
https://staging.imis-prototyp.de/app/send-to-quarantine
**Browser**
Chrome 
**Screenshot**
![image](https://user-images.githubusercontent.com/65396262/82190928-116bb380-98f2-11ea-97cc-6b0f5442fe3a.png)

**Comment by wobkenh** [comment]
Buttons sind jetzt nicht mehr absolut auf Screens < 1300 px
