### ISSUE TITLE
Prefilled Form-Text überlappt Feld

### ISSUE THREAD

**Issue by philipplott-ship-it** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#338]
**Beschreibung**
Der vorausgefüllte Text wie ein Datum erfasst werden soll, ist abgeschnitten (siehe Screen)

**Eingeloggt als**
DPH (Department of Health)
**Link**
https://staging.imis-prototyp.de/app/request-quarantine
**Browser**
 Edge
**Screenshot**
![image](https://user-images.githubusercontent.com/65396262/82192591-7c1dee80-98f4-11ea-83d8-f0df871cbd14.png)

**Comment by JonasCir** [comment]
Hier kann #308 am besten gleich mit gefixt werden, ist die selbe View

**Comment by btobi** [comment]
Habe den Placeholder für das Datumsfeld schon in #301 angepasst. Hier muss nichts mehr gemacht werden.
