### ISSUE TITLE
Unlogische Datenerfassung/Fehler beim Registrieren eines Patienten

### ISSUE THREAD

**Issue by gembez** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#345]
**Beschreibung**
Kann Keinen Patienten anlegen. Angaben machen zum Teil inhaltlich keinen Sinn. Z.b. Geburtsdatum und Sterbedatum in der Zukunft. Falscher Userinput wird aber nicht abgefangen.
**Eingeloggt als**
DPH (Department of Health)
**Link**
https://staging.imis-prototyp.de/app/register-patient
**Browser**
Chrome
**Screenshot**

![image](https://user-images.githubusercontent.com/25324059/82222787-134d6b00-9922-11ea-8a85-93cc57539331.png)
![image](https://user-images.githubusercontent.com/25324059/82222814-1a747900-9922-11ea-923f-43706f576a28.png)
![image](https://user-images.githubusercontent.com/25324059/82222846-23fde100-9922-11ea-8f2f-3c83d0f40b89.png)

![image](https://user-images.githubusercontent.com/25324059/82222636-d97c6480-9921-11ea-8951-f0063636da9d.png)

**Comment by lordpomeroy** [comment]
As far as i can see the date field "patientHospitalized" is not filled but the checkbox selected. This might lead to an issue with a "Null Pointer"

**Comment by JonasCir** [comment]
Related to #52

**Comment by JonasCir** [comment]
#52 tracks field value issues and error is related to hospitalization
