### ISSUE TITLE
Cannot find user in "Alle Patienten" view

### ISSUE THREAD

**Issue by gembez** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#346]
**Beschreibung**
Cannot search for an user that should be available. No results found, even though search is executed with different valid attributes like Vorname, Nachname, Stadt, PLZ ...
**Eingeloggt als**
 DPH (Department of Health)
**Link**
https://staging.imis-prototyp.de/app/patient-list
**Browser**
Chrome

![image](https://user-images.githubusercontent.com/25324059/82224469-2a8d5800-9924-11ea-833e-5cc634c3bb87.png)
![image](https://user-images.githubusercontent.com/25324059/82224682-717b4d80-9924-11ea-9d25-3a7bfa9340c0.png)

**Comment by JonasCir** [comment]
Comment from @t0bska #369 
Hinweis: Die (Erweiterte-) Suche hat bisher noch nie richtig funktioniert. (vgl. auch #352)

Zudem:

    Für die Eingabe in das Suchfeld gilt dasselbe, wie in Issue #375 erwähnt: Die Reihenfolge der Suchergebnisse sollte (standardmäßig) nicht nach Name, sondern nach Relevanz erfolgen.
    Das Zurücksetzen der Filter funktioniert nicht. (Man suche nach Geschlecht männlich, dann wieder nach Geschlecht alle)
    Die Filter liefern keine brauchbaren / korrekten Ergebnisse
    Die erweiterte Suche ist z.Z. kompletter Müll

**Comment by JonasCir** [comment]
1. Die Volltextsuche über alle (angezeigten) Felder sollte für die Simulation funktionieren
2. Erweiterte Suche is _nice to have_ für die Simulation

**Comment by lordpomeroy** [comment]
Closed for now as search seems to be working at the moment
