### ISSUE TITLE
[Patienten Details] Fallstatus kann nicht geändert werden

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#365]
Der Fallstatus wird bei der Registrierung unter "Krankheit und Zustand" gesetzt.

Inder der Patienten Detailsübersicht kann dieser Status aber nicht mehr geändert werden, weder über "Daten ändern" noch im "Aktionen Menü".

Die folgenden Felder müssen editierbar sein oder **müssen noch angezeigt werden**:

- [x] Fallstatus

- [x] Infos zur Hospitalisierung

- [x] Vorerkrankungen

- [x] Exposition fehlt komplett in den Details

- [x] Symptome sind nicht editierbar. Andere Freitextfeld wird nicht angezeigt, Checkboxen fehlen

- [x] Verstorben + Todesdatum wird in Details nicht angezeigt

- [x] Per Freitext eingegebener bei Beruf bei Registrierung wird nicht angezeigt  

- [x] Reihenfolge der Felder wie Allgemeine Angaben, Wohnort, Aufenthaltsort, falls von Wohnort abweichend etc sollten die gleiche Reihenfolge wie bei der Registrierungsmaske haben

- [x] Krankheit und Zustand fehlt komplett

- [x] Hospitalisierung wird nicht angezeigt

**Comment by btobi** [comment]
Gleiches gilt wohl auch für

- Infos zur Hospitalisierung
- Vorerkrankungen
- Exposition

Ich denke am einfachsten wäre, dem User das Formular zur Patientenregistrierung, vorausgefüllt mit dem jew. Patienten zur Verfügung zu stellen, anstatt das Formular in viele kleine zu splitten.

Was denkst du, @JonasCir?

**Comment by JonasCir** [comment]
Du meinst, dass man Stammdaten und Falldaten merged? Dass könnte man machen. Verlauf und
Infektionskette würde ich aber getrennt behalten.

**Comment by btobi** [comment]
Genau, Infektionskette wird ja sowieso über die Kontakte gepflegt. Alles andere ist aber schon bei der Patientenregistrierung in einem Formular, also spricht von meiner Seite nichts dagegen, das beim Bearbeiten auch so zu machen. Zumindest mal übergangsweise. 

In Zukunft kann man sich immer noch überlegen, ob man zu den jeweiligen Einzelthemen, wie Vorerkrankungen und dergleichen eigene Formulare zum Editieren anbietet.

**Comment by JonasCir** [comment]
Jupp dann lass das so machen :+1:

**Comment by JonasCir** [comment]
@btobi Ich hab die Description angepasst. Es gibt eine große Diskrepanz zwischen dem was wir bei der Registrierung abfragen und was wir in Details anzeigen bzw zum editieren frei geben.

Not a Vue expert at all but:

Gibt es eine Möglichkeit eine Vue componente zu schreiben, die sowohl bei der Registrierung als auch in den Details benutzt wird und alle Felder kennt? Damit können wir in Zukunft verhindern, dass eine Änderung an 2 Stellen gemacht werden muss und die zwei pages auseinander driften.

**Comment by wobkenh** [comment]
> Gibt es eine Möglichkeit eine Vue componente zu schreiben, die sowohl bei der Registrierung als auch in den Details benutzt wird und alle Felder kennt?

Ja. Bei den Stammdaten ist das auch bereits so. Ich versuch mal, das auch bei den anderen Bereichen umzusetzen sofern möglich und sinnvoll

**Comment by wobkenh** [comment]
PR ist offen.

Zwei Punkte waren mir jetzt unklar:
- Zum Punkt, dass der Freitext vom Beruf nicht angezeigt wird... Bei mir funktioniert das in Staging schon, mache ich etwas anders?
- Beim Bearbeiten der Falldaten updated das Backend das Meldedatum nicht. Sollen Nutzer das Meldedatum anpassen können? Dann müsste das im Backend noch angepasst werden (Frontend sendet es schon aktualisiert mit) Oder soll die nachträgliche Bearbeitung des Meldedatums im Frontend disabled werden?

**Comment by JonasCir** [comment]
@wobkenh 
1. Du hast Recht, Freitext Beruf wird angezeigt
2. Das Meldedatum sollte man ändern können, man kann sich ja auch einfach bei der Registrierung verklicken.
