### ISSUE TITLE
[Erweiterte Suche] funktioniert nicht

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#369]
1. Suche Patient mit PLZ
2. Kopiere PLZ in das Erweiterze Suche PLZ Feld
3. Der User wird nicht gefunden

**Comment by TheJKM** [comment]
Nicht nur die PLZ, auch weitere Suchkriterien funktionieren nicht. Es wird immer nur "Joe Doe" gefunden (wenn die Kriterien passen).

Hinweis an die Devs: der CSV-Export liefert auch nur "Joe Doe". Könnte das selbe Problem sein.

**Comment by t0bska** [comment]
_Hinweis:_ Die (Erweiterte-) Suche hat bisher noch nie richtig funktioniert. (vgl. auch #352) 

**Zudem:** 
- Für die Eingabe in das Suchfeld gilt dasselbe, wie in Issue #375 erwähnt: Die Reihenfolge der Suchergebnisse sollte (standardmäßig) nicht nach Name, sondern nach Relevanz erfolgen.
- Das Zurücksetzen der Filter funktioniert nicht. (Man suche nach Geschlecht männlich, dann wieder nach Geschlecht alle)
- Die Filter liefern keine brauchbaren / korrekten Ergebnisse
- Die erweiterte Suche ist z.Z. kompletter Müll

**Comment by t0bska** [comment]
Verknüpft mit #263 ?

**Comment by JonasCir** [comment]
closing in favor of #346
