### ISSUE TITLE
[Patient registrieren] Pflichtfelder (weitgehend) entfernen

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#374]
z.Z. lässt sich beispielsweise niemand ohne E-Mail-Adresse registrieren. Auf einer Labormeldung steht aber keine E-mail-Adresse drauf. Daher sollten nur die absolut notwendigen Daten (Name, Anschrift) Pflichtfelder sein.

**Comment by t0bska** [comment]
Kleiner Nachtrag: z.B. bei einem Verstorbenen braucht man keine Telefonnummer mehr und eine E-Mail kann man ihm auch nicht schreiben. ;-)

**Comment by Jochen-Sch** [comment]
In der Tat sollte zumindestens email und Telefonnummer optional sein (gilt für die initiale Registrierung sowie auch das Ändern von Stammdaten)
