### ISSUE TITLE
UI Quick Fixes

### ISSUE THREAD

**Issue by HellerDominik** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#379]
- [x] Seite 1 und 3 der Selbstregistrierung bitte linksbündig machen

![image](https://user-images.githubusercontent.com/63474971/82548242-4af32780-9b5b-11ea-9511-cb46282f8197.png)

![image](https://user-images.githubusercontent.com/63474971/82554991-387eeb00-9b67-11ea-9724-d6d38869ec7c.png)

- [ ] Auf Seite 2 bitte andere/sonstige mit Textbox.
![image](https://user-images.githubusercontent.com/63474971/82555050-5ba99a80-9b67-11ea-90f0-e9e3eb39a9c1.png)

Gerne das Andere: aus 3 Risiken übernehmen

![image](https://user-images.githubusercontent.com/63474971/82555151-85fb5800-9b67-11ea-93c3-3f6f4e8c78c8.png)

- [x] Aus Seite 4 soll das Dropdown Menü Berufe 2 Änderungen bekommen.
![image](https://user-images.githubusercontent.com/63474971/82555250-bb07aa80-9b67-11ea-9988-15e8bffc0501.png)

1. "Pflegepersonal" umbenennen in "Krankenpfleger/in"
2. Letzten Punkt der Liste "Keiner der genannten (bitte unten eingeben)" ändern in "Anderer"
3. Alphabetische Einträge (bis auf "Anderer", welcher die Textbox darunter aktiviert und deshalb zum Schluss stehen muss)

- [x] Seite 5 sollte als Waypoint in der Liste oben dargestellt werden

![image](https://user-images.githubusercontent.com/63474971/82555642-6b75ae80-9b68-11ea-9421-d80795101be8.png)

Text dazu ✔️ Abschließen

- [x] Auf Seite 5 bitte den Text "Sie haben es fast geschafft!" ändern in "Abschließen"
- [x] 3 Änderungen am Button Daten übermitteln
![image](https://user-images.githubusercontent.com/63474971/82555891-f5be1280-9b68-11ea-821f-22c46169f1c3.png)

1. Icon austauschen gegen ein Senden Icon (in der Regel ein Papierflieger). Den habe ich in der Ant Lib gerade nicht gefunden. Wenn das zeitaufwändig ist funktioniert auch ein Check auf dem Button, der Papierflieger wird allerdings eher mit Senden assoziiert.
2. Text ändern in "Absenden"
3. Position des Buttons ändern auf die Position des Weiter-Buttons der vorherigen Seiten 
![image](https://user-images.githubusercontent.com/63474971/82556115-649b6b80-9b69-11ea-81f9-961b75a5fb8a.png)

- [x] Auf Seite 4 der Selbstregistrierung bitte den Begriff optional überall entfernen. Mit dem roten Stern kommunizieren wir bereits ausreichend bei welchen Feldern es sich um Pflichtfelder handelt. 
![image](https://user-images.githubusercontent.com/63474971/82556199-8f85bf80-9b69-11ea-810a-3e2e12ad676f.png)

- [x] In der Patientenregistrierung redundante Texte löschen

1. Bitte zutreffendes ankreuzen
2. Welche Symptome weist der Patient/die Patientin auf?
3. Welche Vorerkrankungen und Risikofaktoren liegen vor?

- [x] In der Patientenregistrierung Checkboxen alphabetisch sortieren und untereinander anordnen
1. Symptome 
2. Vorerkrankungen und Symptome
Bei beidem, wie immer, "Andere" mit Textfeld zum Schluss

- [x] In der Patientenübersicht das Icon zum bearbeiten (derzeit Logout und am linken Seitenrand) ändern. Bitte  nach analog zur Kontaktpersonenliste Männchen in blau.
- [x] Probe zuordnen: "Proben-Materia" -> "Probenmaterial"
- [x] Probe zuordnen: Testtyp und Probenmaterial vorauswählen: PCR & Rachenabstrich
- [x] Probe zuordnen: "Abnahmedatum" -> "Probendatum"
- [x] Probe zuordnen: Probendatum als Pflichtfeld, da es sowieso nicht freigelassen werden kann
- [x] Patientendetails: Kontaktfeld ist zu klein für eine "normale" E-Mail Adresses
- [x] Patientendetails: Alle Boxen in eine Zeile sollten gleich hoch sein
- [ ] Patientendetails -> Falldaten: Die Testypen Antkörper und PRC sind nicht gleich ausgerichtet
- [ ] Patientenregistrierung: Vorerkrankungen & Risikofakoren: "ARDS" & "Beatmungspflichtige Atemswegserkrankung" ist nicht in den oberen Spalten mit ausgerichtet
- [ ] Patientenregistrierung: Im Fallstatus sollte der Verdachtsfall als einziges auswählbar sein (siehe Ticket #389 für die spätere Korrektur)
- [ ] Statistiken: CSV Export geht nicht, Button ausblenden
- [ ] In Quarantäne senden: Der Text oben zählt falsch. Entweder fixen, oder ausbauen. Aktuell werden die PLZ Blöcke gezählt und nicht die Patienten, so wie es aussieht

**Comment by syntakker** [comment]
Für Selbstregistrierung bis auf zwei Punkte umgesetzt, s. pull request #409.

**Comment by syntakker** [comment]
Moment, da ist nur der Teil in der Selbstregistrierung umgesetzt, und auch da fehlt noch eine Textbox.
Bitte wieder öffnen.

Folgendes ist, soweit ich sehen kann, noch nicht umgesetzt:

>     * Auf Seite 2 bitte andere/sonstige mit Textbox.
>       ![image](https://user-images.githubusercontent.com/63474971/82555050-5ba99a80-9b67-11ea-90f0-e9e3eb39a9c1.png)
> 
> 
> Gerne das Andere: aus 3 Risiken übernehmen

ebenso alles ab:
>     * In der Patientenregistrierung redundante Texte löschen
> 
> 
>     1. Bitte zutreffendes ankreuzen
> 
>     2. Welche Symptome weist der Patient/die Patientin auf?
> 
>     3. Welche Vorerkrankungen und Risikofaktoren liegen vor?
> 
> 
>     *
...

**Comment by syntakker** [comment]
Textboxen wollte ich hier nicht ohne weitere Abstimmung ergänzen, weil das auch das Datenmodell betrifft (bin neu hier :-) ).
Zu weiteren Fixes werde ich heute wahrscheinlich auch nicht mehr kommen.

**Comment by JonasCir** [comment]
@syntakker ist wieder offen :smiley:
