### ISSUE TITLE
Client side authentication,

### ISSUE THREAD

**Issue by Maccodonaldo** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#38]
Unabhängig von der serverseitigen Authentifizierung sollte ein 
* Authguard
* Authservice
* HttpInterceptor 
vorbereitet um die serverseite schnell im client umzusetzten

**Comment by jojo19893** [comment]
was braucht ihr vom backend?

**Comment by t0bska** [comment]
Verknüpft mit #73

**Comment by t0bska** [comment]
Wenn man auf zum Prototypen klickt auf der Landing-Page sollte ein UI erscheinen mit Login (der kann von der GUI geprüft werden, das reicht)

**Comment by wobkenh** [comment]
Würde mich wohl an der Aufgabe versuchen wollen.
Denke es sollte dann einen Public Bereich (Landingpage und Öffentliche Statistiken) und einen mit Login abgesicherten Bereich geben. Man müsste mal schauen, ob man auch direkt das Rollenkonzept (welcher eingeloggte User sieht welche Navigationseinträge) angeht.

Würde wohl auch direkt die Backendanbindung vornehmen - die erfolgt ja aktuell (#84 ).

**Comment by wobkenh** [comment]
Pull request steht ( #105 )

**Comment by wobkenh** [comment]
Close, da der PR durch ist
