### ISSUE TITLE
Land Dropdown

### ISSUE THREAD

**Issue by HellerDominik** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#381]
Derzeit ist das Land in der Selbstregistrierung und Patientenregistrierung noch nicht komplett gefüllt. 
Bitte vorausgefüllt "Deutsch", oberster Eintrag der Liste "Unbekannt", danach die endliche Liste der Länder alphabetisch.

**Comment by Jochen-Sch** [comment]
Idealerweise Länderliste aus dem Backend ziehen inkl. Sprachabhängigkeit wobei übertragener und gespeicherter Wert der ISO code sein sollte (Default 'DE' kann dann im Client gesetzt werden).
Den Wert unbekannt könnte man ebenfalls im Client hinzufügen und ggf. wegnehmen sobald die Adresse gefüllt ist oder statt unbekannt einfach blank zulassen - das hängt davon ab ob die Adresse an sich optional ist oder nicht). Sofern die Adresse mandatory is macht "unbekannt" aus meiner Sicht keinen Sinn.
