### ISSUE TITLE
Frage nach Beschwerden mit Abhängigkeit versehen

### ISSUE THREAD

**Issue by HellerDominik** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#384]
![image](https://user-images.githubusercontent.com/63474971/82557756-a0840000-9b6c-11ea-8989-81f3df307bd3.png)

Solange keine Symptome eingetragen sind sollte die Frage nach den Beschwerden nicht anklickbar sein.  
Erst danach werden die 2 ([bzw. 3](https://github.com/ImisDevelopers/1_011_a_infektionsfall_uebermittellung/issues/383)) Optionen auswählbar.  
  
Wenn bei den Beschwerden eine Option ausgewählt ist, danach aber alle Checkboxen der Symptome wieder unchecked werden, muss jede Auswahl der Beschwereden Radiobuttons gelöscht werden (zurück auf default).

**Comment by Jochen-Sch** [comment]
Ja, in der Tat ... sollte kombiniert werden mit der option "nicht bekannt" für das Symptomauftreten (analog zu Impfung)
