### ISSUE TITLE
PatientList-Csv-Export: Hausnummer null, PLZ nicht exportiert

### ISSUE THREAD

**Issue by syntakker** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#401]
Reproduce:
https://staging.imis-prototyp.de/app/patient-list -> CSV exportieren

- Hausnummer ist null (evtl. über regex?)
- PLZ wird nicht exportiert
- "Stadt" doppelt (Geburtsstadt vs. Wohnort?)

```csv
ID;Vorname;Nachname;Geschlecht;Status;Geburtsdatum;Stadt;E-Mail;Telefonnummer;Straße;Hausnummer;Stadt;Versicherung;Versichertennummer
48F74B12;Cornelius;Bauer;male;SUSPECTED;1925-02-15;Kirkel;c.bauer@example.de;5455884506;Schernerweg 44;null;Kirkel;KNAPPSCHAFT;U796999048
DC03500A;Peter;Bauer;male;SUSPECTED;1926-08-27;Dudweiler;p.bauer@example.de;310105989334;Waldstraße 22;null;Dudweiler;DAK Gesundheit;Q228155179
0E475F5C;Hans;Bauer;male;SUSPECTED;1939-07-20;Kirkel;h.bauer@example.de;910010413797;Nordufer 61;null;Kirkel;Barmer;Z725611522
0B13B1F8;Peter;Bauer;male;SUSPECTED;1967-07-22;Riegelsberg;p.bauer@example.de;5280924287;Südweg 59;null;Riegelsberg;KNAPPSCHAFT;N252252010
```
*Update*: Stadt ist tatsächlich doppelt, Geburtsort wird nicht erfasst.

**Comment by syntakker** [comment]
Ist dieser CSV-Export mit anderen Schnittstellen abgestimmt bzw. gibt's dafür eine Spezifikation?

**Comment by lordpomeroy** [comment]
Nein dafür gibt es aktuell keine Spezifikation. Nach der Simulation wissen wir da vielleicht mehr.

**Comment by syntakker** [comment]
Konservativer Fix in pull request #406.

patient.houseNumber steht zwar in der API, wird aber scheinbar nirgendwo befüllt.
