### ISSUE TITLE
Fragenkatalog für die Simulation beim GA in Saarbrücken

### ISSUE THREAD

**Issue by HellerDominik** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#421]
## Vor der Simulation

* Mit welchen Tools arbeiten sie derzeit? 
* Welche Tätigkeiten führen sie mit diesen Tools aus?
* Welche Aufgabe machen sie am Häufigsten?
* Welche Aufgabe macht ihnen am wenigsten Spaß?
* Welcher Schritt dauert unnötig lange? 
* Mit welcher Änderung können sie die meiste Zeit sparen?  
* Wer sind ihre regelmäßigen Ansprechpartner innerhalb und außerhalb des Gesundheitsamts?
* Wie können sie Arbeitsschritte ihrer Kollegen nachvollziehen?

## Nach der Simulation

* Was hat ihnen gefallen und warum? 
* Was ist ihnen schwer gefallen und warum?
* Was haben sie anders erwartet? 
* Wo hat IMIS noch Verbesserungsbedarf?
* Welche Funktionen fehlen noch und warum? 
* Wenn sie sich etwas wünschen dürften, was wäre das?

## Allgemein

* Grundsätzlich sind diese Fragen nicht der Reihe nach zu beantworten und deshalb nicht durchnummeriert. Der Gesprächsfluss bestimmt welche Frage gerade passt.  
* Es handelt sich bei diesen Fragen um offene Fragen, von einer Frage die mit Ja/Nein zu beantworten ist, können wir in einer qualitativen Befragung nur wenig lernen. 

Wenn ihr noch Vorschläge habt, gerne mit eintragen.

**Comment by syntakker** [comment]
- Welche Schnittstellen anderer Tools müßte IMIS bedienen können?
- Welche wiederkehrenden Tätigkeiten sind so schematisch, dass sie als Prozess in einem Tool abgebildet werden können?

**Comment by btobi** [comment]
@HellerDominik Dieses Issue können wir schließen oder? Die Fragen sollten auf jeden Fall in ein Dokument auf Google Drive.
