### ISSUE TITLE
Patient List Caching/Display Issue for Updated Patient Data

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#428]
When changing patient master data or test results, the updated data is not available within the patient list subsequently (even after page refresh or logout and new login)

Steps to reproduce: 
Create a new contact for a patient (Tab Infektionskette) do not chose an existing patient but enter new last name first name. After confirmation go to the details of that contact and complete address data and date of birth.
Go to Patient List (Alle Patienten) and search for that patient - observe that city and age is not determined. When navigating to the details, the data is there. Also an Advanced Search for Patients with the City entered correctly find the newly maintained patient correctly.

Similar the Patient Status is always shows as 'Verdachtsfall' even after positive test.

The search for Quarantänestatus seems to not work any more which could be related to the same issue?

**Comment by Jochen-Sch** [comment]
To be determined from a technical perspective whether a fix could endanger existing functionality and judge whether we can fix this still before simulation on pilot

**Comment by jojo19893** [comment]
@LeonardKoll  / @btobi  didn't we fix this?

**Comment by btobi** [comment]
The fix was merged to dev already, but somehow a merge by @MichaelSp reverted the changes. I cannot explain this. I will try to undo this.
