### ISSUE TITLE
Login to IMIS Staging failing

### ISSUE THREAD

**Issue by jabrandes** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#442]
**Describe the bug**
Cannot log into IMIS Staging (<https://staging.imis-prototyp.de>).

**To Reproduce**
1. Go to <https://staging.imis-prototyp.de/login>
2. Enter username `test_testing_site` and password `asdf`
3. Click on `Einloggen`
4. Nothing happens; web console shows an uncaught exception, and net analyzer shows 403 status code for login response

**Expected behavior**
Login succeeds and the IMIS UI with action menu shows up.

**Desktop:**
 - OS: Linux (Ubuntu 18.04)
 - Browser: Firefox 76.0.1

**Additional context**
Request:
```
Host: staging.imis-prototyp.de
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
Origin: https://staging.imis-prototyp.de
Content-Length: 50
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
TE: Trailers

{"username":"test_testing_site","password":"asdf"}
```

Response headers:
```
HTTP/2 403 Forbidden
cache-control: no-cache, no-store, max-age=0, must-revalidate
date: Wed, 27 May 2020 22:09:39 GMT
expires: 0
pragma: no-cache
strict-transport-security: max-age=31536000 ; includeSubDomains
vary: Accept-Encoding
vary: Origin
vary: Access-Control-Request-Method
vary: Access-Control-Request-Headers
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
content-length: 0
X-Firefox-Spdy: h2
```

**Guess of problem source**
Probably the database as the repeated source of issues. It might be worth investigating whether all deployments of CI use a separate database, since a common database may well be the culprit due to different IMIS processes erroneously mutating another's database state (e.g. re-initializing database on startup, or potentially failing to do so).

**Comment by Jochen-Sch** [comment]
Trying on Swagger UI gives the same response:
cache-control: no-cache, no-store, max-age=0, must-revalidate  content-length: 0  date: Wed, 27 May 2020 22:44:30 GMT  expires: 0  pragma: no-cache  strict-transport-security: max-age=31536000 ; includeSubDomains  vary: Accept-Encoding, Origin, Access-Control-Request-Method, Access-Control-Request-Headers  x-content-type-options: nosniff  x-firefox-spdy: h2  x-frame-options: DENY  x-xss-protection: 1; mode=block 

Question (not a technical expert): 403 could mean that the user cannot be authenticated as the DB is not there but couldn't it also mean that the backend server or webserver (not the DB) has an issue instead (as DB is run by Google)?

**Comment by jabrandes** [comment]
It has to be some kind of error related to the deployment of the IMIS Staging system, since the dev branch code can be run without any problems on my local machine.

**Comment by JonasCir** [comment]
@MichaelSp @jojo19893

**Comment by LeonardKoll** [comment]
Ich hatte gerade das DB Issue lokal und habe hier einen Screenshot reingestellt. Falls die vermutung besteht dass es da einen Zusammenhang gibt: #448

**Comment by jabrandes** [comment]
Seems to be resolved, if at least for now.
