### ISSUE TITLE
Database connection crashes

### ISSUE THREAD

**Issue by LeonardKoll** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#448]
**Describe the bug**
The database connection crashes without predictable behavior. 

**Screenshots**
![image](https://user-images.githubusercontent.com/20996097/83156708-063f3180-a103-11ea-8341-132aaee92fd6.png)
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms.

Maybe helpful:
https://stackoverflow.com/questions/51665095/hikari-unable-to-acquire-jdbc-connection

**Comment by jabrandes** [comment]
In what context did you produce this error? When testing locally or has it something to do with one of the remote IMIS servers (Staging)?

**Comment by jabrandes** [comment]
Just to exclude the obvious, is/was the database running when the error happened?

**Comment by jojo19893** [comment]
I think the problem could be in the `SeachService` we create new ` EntityManagers` but never close them
