### ISSUE TITLE
Videobeschreibung anpassen

### ISSUE THREAD

**Issue by lordpomeroy** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#46]
Mit DevPost abgleichen.

**Comment by Seal33** [comment]
*Vorschlag*

Im Rahmen des #WirVsVirusHack Hackathons der Bundesregierung erstellt: wirvsvirushackathon.org
Herausforderung 11 - Infektionsfallübermittlung 

Die COVID-19 Pandemie stellt für das bestehende Infektionsmeldewesen in Deutschland eine immense Herausforderung dar. Ärzte und über 400 Gesundheitsämter benutzen gegenwärtig einen uneinheitlichen Mix aus Fax, E-Mails und Excel Tabellen um Fälle zusammenzutragen.
Unsere Software Lösung IMIS setzt genau an diesem Punkt an und zentralisiert die Datenerfassung von Infektionen mit einer modularen und einfach zu benutzenden Web-App, um Ärzte, Gesundheitsämter und andere Institutionen zu entlasten.

Weitere Infos findet Ihr DevPost: https://devpost.com/software/imis-infektions-melde-und-informations-system

Live-Prototyp: http://imis-prototyp.de

Für die Umsetzung haben wir Unterstützung durch eine Darstellung des aktullen Prozesses erhalten, vielen Dank dafür. Diesen Prozess findet ihr hier: https://covidmeldeprozess.de/ 

gemafreie Musik von www.frametraxx.de

**Comment by JonasCir** [comment]
Vielleicht den GItHub Repo Link noch einfügen?

**Comment by bmikaili** [comment]
Created as part of the #WirVsVirusHack Hackathons of the federal government: wirvsvirushackathon.org

Challenge 011_InfectionCaseTransmittion

The COVID-19 pandemic represents an immense challenge for the existing infection reporting system in Germany. Doctors and more than 400 health authorities are currently using an inconsistent mix of fax, e-mail and Excel spreadsheets to compile cases.
Our software solution IMIS addresses this issue and centralizes the data collection of infections with a modular and easy to use web-app to relieve doctors, health authorities and other institutions.

Further information can be found at DevPost: https://devpost.com/software/imis-infektions-melde-und-informations-system

GitHub: https://github.com/imis-Infektionsfall-uebermittellung/

Live prototype: http://imis-prototyp.de

For the implementation we received support by an illustration of the current process, thank you very much. You can find this process here: https://covidmeldeprozess.de/

Royalty Free Music from www.frametraxx.de

**Comment by Jochen-Sch** [comment]
Ich würde vorschlagen noch folgenden Punkt an den ersten Absatz anzuhängen:

[DE] Ausserdem haben Entscheidungbeteiligten schneller Zugriff auf eine genauere Datenlage in Bezug auf die bekannten Infektionen einer Region oder des ganzen Landes.

[EN] In addition decision making parties will have faster acces to more precise data in regards to the the current state of infection for regions or the whole country.

**Comment by lordpomeroy** [comment]
Hab mal aktualisiert.
Bitte einfach schauen und nochmal hier updaten.

**Comment by Seal33** [comment]
Fügst du die Kontakt-email imis-team@gmx.de hinzu?
