### ISSUE TITLE
Patient registration missing on Staging (DEV)

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#472]
**Describe the bug**
Patient Registration lacks complete person data
https://staging.imis-prototyp.de/

**Screenshots**
Patient Reg
![IMIS Bug - Patient Reg](https://user-images.githubusercontent.com/62520548/83946766-1cd83d80-a813-11ea-97d6-0a2a00096c00.PNG)

 - OS: Win64 
 - Browser Firefox 68.7.0esr / Edge / Chrome

**Comment by syntakker** [comment]
Fixed in commit ccccd2e.
