### ISSUE TITLE
Client Docker build errors on dev

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#478]
**Describe the bug**
Client Docker build errors on `dev`

**To Reproduce**

`
git checkout dev &&
cd client &&
docker build  -t imis/sormas-client .
`

**Expected behavior**
Build passes

**Comment by jabrandes** [comment]
@JonasCir Details?! :see_no_evil:

**Comment by JonasCir** [comment]
ERROR in /app/src/router/index.ts(53,35):
53:35 An interface can only extend an object type or intersection of object types with statically known members.
    51 | }
    52 | 
  > 53 | export interface AppRoute extends RouteConfig {
       |                                   ^
    54 |   meta?: {
    55 |     navigationInfo?: {
    56 |       icon: string

 error  in /app/src/router/index.ts

**Comment by JonasCir** [comment]
Or
ERROR in /app/src/router/index.ts(88,5):
88:5 Type '{ name: string; path: string; component: ExtendedVue<Vue, State, { handleSubmit(): void; }, unknown, Record<never, any>>; meta: { navigationInfo: { icon: string; title: string; authorities: ("ROLE_TEST_SITE" | ... 2 more ... | "ROLE_DEPARTMENT_OF_HEALTH")[]; showInSidenav: true; }; }; }' is not assignable to type 'AppRoute'.
  Object literal may only specify known properties, and 'name' does not exist in type 'AppRoute'.
    86 |   },
    87 |   {
  > 88 |     name: 'register-patient',
       |     ^
    89 |     path: 'register-patient',
    90 |     component: RegisterPatient,
    91 |     meta: {

 error  in /app/src/router/index.ts

**Comment by JonasCir** [comment]
Bunch of similar errors

**Comment by JonasCir** [comment]
All errors have to do with `AppRoute` imported from `vue-router`

**Comment by JonasCir** [comment]
@jabrandes I hope to reproduce in #479

**Comment by JonasCir** [comment]
@jabrandes I think the issue is caused by a dependency. Clean clone and build on this repo's master fails as well and I'm certain that it worked a couple of days ago, so it is likely not a code change from our side

**Comment by jabrandes** [comment]
You mean like since one or two weeks before? Well, guess what: Its not a bug...

From commit <https://github.com/vuejs/vue-router/commit/dab86c5263c077b486de6438927740a78c72c71c>
![grafik](https://user-images.githubusercontent.com/16663164/84939657-f2be2f80-b0de-11ea-8591-1830692a52d3.png)
