### ISSUE TITLE
Hinweis zum Datenschutz im Prototyp

### ISSUE THREAD

**Issue by lordpomeroy** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#49]
- [x] Hinweis zum Datenschutz
- [ ] Wenn eine Verküpfung zu einer Datenbank erstellt wird sollte nur ein Teil der Daten eingetragen werden, damit wir dort kein Problem bekommen

**Comment by bmikaili** [comment]
Banner ist da, Daten werden randomisiert.
