### ISSUE TITLE
Test-Typ hinzufügen

### ISSUE THREAD

**Issue by Seal33** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#56]
Bald kommen vorr. schnelltests usw. hinzu. Dies sollten wir beachten

**Comment by Seal33** [comment]
Es bleibt zu klären, wie wir mit Schnelltests verfahren. Wer trägt diese ein? Das labor fällt ja schonmal weg. Sollten teststellen und ärzte eintragen können, ob ein User einen schnelltest gemacht hat?
Also einfach eine Verknüpfung user-id mit dem ergebnis

**Comment by t0bska** [comment]
in #87 enthalten
