### ISSUE TITLE
Open Source Lizenz

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#57]
MIT, APACHE, etc

**Comment by luxn** [comment]
https://tldrlegal.com/

**Comment by MichaelSp** [comment]
I'd vote for https://tldrlegal.com/license/do-what-the-fuck-you-want-to-but-it's-not-my-fault-public-license-v1-(wtfnmfpl-1.0) :D

TBH: I don't care

**Comment by bmikaili** [comment]
Einfach MIT und gut ist?

**Comment by lordpomeroy** [comment]
Should we make our work available for later commercial use?

**Comment by MichaelSp** [comment]
[Open Core](https://en.wikipedia.org/wiki/Open-core_model)
