### ISSUE TITLE
Efficient task flow and task assignment

### ISSUE THREAD

**Issue by lukaskoeller** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#59]
Create a workflow for tasks so they can be, seen, assigned and completed while being visible for everyone. 

**Potential Benefits:**
- No double work of tasks
- Everybody is aware who is doing what at the moment 
- Task can be better aligned to each other and better coordinated.

**Comment by t0bska** [comment]
Wir sind dran. Zur Übersichtlichkeit geschlossen.
