### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by MichaelSp** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#61]
Github Org und Repo könnten etwas kürzer sein.

**Comment by Maccodonaldo** [comment]
Ich würde die Org erstmal auf Imis umbennen. Das Repo vielleicht erst nach dem Judging, ok  ?

**Comment by MichaelSp** [comment]
Alles klar

**Comment by Maccodonaldo** [comment]
Links to your previous organization profile page, such as https://github.com/previousorgname, will return a 404 error. We recommend you update links to your organization from other sites, such as your LinkedIn or Twitter profiles.
API requests that use the old organization's name will return a 404 error. We recommend you update the old organization name in your API requests.
There are no automatic @mention redirects for teams that use the old organization's name.

Bitte beachten

**Comment by Maccodonaldo** [comment]
Werde auch in einer Woche den Namen ändern

**Comment by Seal33** [comment]
Ich dachte IMIS war vergeben, und deshalb IMISDevelopers
