### ISSUE TITLE
Switch Filestorage to Google Cloud Storage solution

### ISSUE THREAD

**Issue by Maccodonaldo** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#62]
Unsere PDFs werden zur Zeit noch als Blop in unserer DB gespeichert, würde gerne Minio vorschlagen. 

[https://min.io/](Minio Open Source S3 Storage)

Das sollte sich eigentlich sehr gut in unsere Plattform integrieren lassen. Passt sehr gut zu unserem Deploymentprozessen und habe damit auch gute Erfahrungen genutzt. Genauso hält uns das die Option offen überall zu Deployen (also auch Regierungsserver).

**Comment by MichaelSp** [comment]
Weil wir auf der google cloud sind vllt. lieber das: https://cloud.google.com/storage 
Bin mir nicht sicher, ob das S3 kompatibel ist. Aber Minio ist soweit ich weiß eine Hosting-Solution. Das würde bei uns ja Google übernehmen

**Comment by luxn** [comment]
Spätestens bei Backups sind Blobs in der DB nervig. Dem Tutorial zu entnehmen sollte Google Cloud Storage auch das S3 Protokoll verstehen können:

https://cloud.google.com/storage/docs/migrating#migration-simple

minio wäre dann unabhängig von der Public Cloud die Lösung.

**Comment by jojo19893** [comment]
ehrlicherweise macht minio jetzt nicht sooooooooo viel sinn weil es eine native integration von GCP storage in spring gibt und das ist denke ich die einfachste lösung erstmal man muss nur die berechtigungen für das storage bucket richtig setzen und schauen wie man die credentials in die container bekommt 
https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.2.RELEASE/reference/html/#google-cloud-storage

**Comment by Maccodonaldo** [comment]
Unabhängig in welcher Form wir das machen, sollte dann das Hauptziel sein den Storage nicht mehr als Blob in der DB zu speichern

**Comment by MichaelSp** [comment]
https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.2.RELEASE/reference/html/#using-cloud-storage is now available
