### ISSUE TITLE
"Andere Vorerkrankung" spezifizieren

### ISSUE THREAD

**Issue by Seal33** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#65]
Wenn ein Patient aufgenommen wird kann bei der Frage nach chronischen Erkrankungen "Andere" angekreuzt werden. Es sollte möglich sein in diesem Fall einen Freitext einzutragen, in dem die genaue Krankheit spezifiziert wird.

**Comment by wobkenh** [comment]
PR ist offen
