### ISSUE TITLE
Change to Nuxt.js (Vue framework) for better SEO

### ISSUE THREAD

**Issue by lukaskoeller** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#66]

**Comment by Parod0ntos3** [comment]
This should not be our priority - currently it is more important to get our prototype done than to be found by google.

-> in long term: good point

**Comment by lukaskoeller** [comment]
Your're completely right @Parod0ntos3. That's why I added it to **Post-deadline**. I didn't intend to implement it in the short-term :)

**Comment by Parod0ntos3** [comment]
Ups, didn't see the tag. :)

**Comment by MichaelSp** [comment]
funny 😁 

![image](https://user-images.githubusercontent.com/448282/77410489-355fbc80-6dbb-11ea-97d9-4c19342a13f4.png)

**Comment by t0bska** [comment]
@lukaskoeller @Parod0ntos3 bitte genauer erläutern. Benefit? 

---
Issue wird ohne weitere Kommentare am 9. April geschlossen
