### ISSUE TITLE
Probe zuordnen Page abschließen

### ISSUE THREAD

**Issue by jojo19893** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#68]
Request zum backend und validieren

**Comment by Parod0ntos3** [comment]
Implementiert

**Comment by lordpomeroy** [comment]
Quick check found:
- [ ] Currently no validation if the patient ID exists (backend)
- [ ] Success popup has static patient and test ID

**Comment by Parod0ntos3** [comment]
Was not released when you tested.

**Comment by bmikaili** [comment]
Can be closed?

**Comment by t0bska** [comment]
Closed in favor of #87
