### ISSUE TITLE
Landing Page on Website

### ISSUE THREAD

**Issue by Seal33** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#73]
Wenn man die URL imis-protoyp.de aufruft wäre es gut, erst auf einer Startseite zur Landen in der ein paar allgemeine Infos zum Projekt stehen. Dort könnte man dann einen großen Knopf in der Art "Prototyp starten" platzieren, sodass man von dort auf die aktuelle website kommt

**Comment by Seal33** [comment]
Landing Page can be found in feature/LandingPage

However, I'm really bad at routing so I was only able to set up an unreliable workaround in that regard. Maybe somebody can look into that?

**Comment by lukaskoeller** [comment]
Ich werde mich mal dran machen @Seal33. Ich würde die Landing Page (LP) jedoch unabhängig von der Webapp gestalten.

**Comment by Seal33** [comment]
Ja, die LandingPage ist grade auch eine component die man im grunde so als standalone irgendwo hinpacken kann. Weiß eben nur nicht wie genau man das dann macht.

**Comment by t0bska** [comment]
Landing-Page erhält rechts ein Login-Feld wie im Landing-Page-concept vorgesehen (darf gern am Ende anders und noch schöner aussehen) Demo-Zugangsdaten Clientseitig prüfen.

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/43952751/77596311-f6855000-6efb-11ea-9266-58a145211b43.png">

**Comment by t0bska** [comment]
Landing Page sollte Fork me on Github o.ä. enthalten um klar zu machen, dass open source und jeder mitmachen kann (siehe #81)

**Comment by lukaskoeller** [comment]
Hier mal das Basislayout der Landingpage. Sie sieht jetzt doch anders aus als von @Seal33 erstellt. Ich hoffe, dass geht klar, sonst sag Bescheid.

Aktueller Stand siehe Screenshot
<img width="1280" alt="Basic Layout - Landing Page" src="https://user-images.githubusercontent.com/10390627/77598182-6c3fea80-6f01-11ea-9a33-7f9b296d2bf6.png">

**Comment by t0bska** [comment]
Dann war ich da nicht auf dem aktuellen Stand. Dann brauchen wir noch eine Login-Page oder ein Popup beim Button "zum Prototypen"

**Comment by lukaskoeller** [comment]
Ich glaub ich war selber auch nicht auf dem neusten Stand...Gab es ein Landingpage Konzept. Wenn ja, wo liegt das ab?

**Comment by t0bska** [comment]
Liegt im geteilten Ordner

**Comment by MichaelSp** [comment]
Evtl noch ein Link zum https://covidmeldeprozess.de/

**Comment by lukaskoeller** [comment]
Fixed a style bug in branch:dev concerning the navigation that had a horizontal overflow. This is connected to the old Landing page.

**Comment by lukaskoeller** [comment]
Although, this bug still exists on https://imis-prototyp.de
