### ISSUE TITLE
Page is scrolling by default

### ISSUE THREAD

**Issue by lordpomeroy** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#75]
The view is 100px larger than 100% even if the page does not need that space.

**Comment by Seal33** [comment]
Window is now always exactly 100% viewport height (at least on "normal" devices)

**Comment by Seal33** [comment]
This fix was reverted with commit https://github.com/ImisDevelopers/1_011_a_infektionsfall_uebermittellung/commit/aa778f7e4de99daea3430a5c16295d87400ed699

So im not sure if I should reimplement it

**Comment by Seal33** [comment]
For me, the only page still scrolling (even though it wouldn't be necessary) is the patient registration. I don't know how other browsers/displays handle that though. In my opinion we can leave it like that for now. What do you think @lordpomeroy ?
