### ISSUE TITLE
Gov contact using business network

### ISSUE THREAD

**Issue by MichaelSp** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#79]
I just learned that our CTO has contact to officials from the Bundesregierung: https://www.linkedin.com/pulse/covid-19-airlift-operation-how-technology-helps-bring-juergen-mueller?articleId=6646423512141582336#comments-6646423512141582336&trk=public_profile_article_view

I'd like to write an email (not sure if he reads or answers) to ask for contact to RKI or Gesundheitsministerium, but things might get out of our teams control if I do so.
Are you OK with this? 
I'll do it if there are  >= 4 👍

**Comment by lordpomeroy** [comment]
Sound good, but I would like to discuss this evening and wait until tomorrow to decide what we are communicating where.

**Comment by t0bska** [comment]
seems to be outdated

**Comment by MichaelSp** [comment]
unfortunately not usefull response so far.

**Comment by JonasCir** [comment]
So can we treat this as a dead end? (asking b/c I have Trello card referencing this issue :) )

**Comment by MichaelSp** [comment]
I'd assume yes, but if things get exciting, I'll let you know.
