### ISSUE TITLE
Fork me on github

### ISSUE THREAD

**Issue by MichaelSp** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#81]
Wie wäre es mit einem 
<img width="149" height="149" src="https://github.blog/wp-content/uploads/2008/12/forkme_left_darkblue_121621.png?resize=149%2C149" class="attachment-full size-full" alt="Fork me on GitHub" data-recalc-dims="1">

Banner auf der Page rechts oben?
Damit machen wir klar, dass das Ding Open Source ist und man mitarbeiten kann. Finde ich immer sympatisch wenn ich das irgendwo sehe...

**Comment by Seal33** [comment]
Überall im prototypen fände ich das etwas zu aufdringlich, aber würde das vlt auf die LandingPage packen!

**Comment by t0bska** [comment]
closed in favor of #73
