### ISSUE TITLE
receive data from CSSTR

### ISSUE THREAD

**Issue by MichaelSp** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#82]
External Patient registration app: 
https://github.com/Julian-Theis/CSSTR

**Comment by Seal33** [comment]
We should contact them. Do you have a DevPost link?

**Comment by MichaelSp** [comment]
https://devpost.com/software/corona-self-service-test-registration-csstr

**Comment by t0bska** [comment]
Outdated because of fusion with CSSTR
