### ISSUE TITLE
GUIs Patienten(selbst)registrierung

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#85]
### Seite "Unterstützte Selbsteinschätzung"

Edit:
- [ ] **Nur kurzer Info-Text (siehe unten!)**

_Aufbauend auf KOPIE der jetzigen Seite "Patient registrieren" mit Datenschutzabfrage._ 

_EDIT: nicht mehr todo:_
- _Titel ändern in "Unterstützte Selbsteinschätzung"_

- _Absendebutton ändern in "Covid-19-Verdacht äußern und Einschätzung anfordern"_

- _Bei multiple-Coice-Fragen in  Infektionskette, Symptome Option  "keine" hinzufügen_

- _Bei Fragen in Vorerkrankungen Optionen "keine" und "ich möchte hierzu keine Angabe machen" hinzufügen_

- _Alle Fragen aus Infektionskette, Symptome zu Pflichtfragen machen_

- _Randomisierung entfernen und nur Daten Nachname, Krankenkasse, Versichertennr, E-Mail, Telefon, Straße, Hausnr bei absenden in ****** ändern_

### Seite "Patient Registrieren (Arzt)"
Aufbauend auf der jetzigen Seite "Patient registrieren"

Todo:
- [ ] Titel ändern in "Patient Registrieren (Arzt)"

- [ ] Datenschutz-Feld entfernen

- [ ] E-Mail-Feld kein Plfichtfeld

- [ ] Absendebutton ändern in "Patient als Covid-19-Verdachtsfall registrieren" 

- [ ] Patient mit Event in Datenbank als Verdachtsfall eintragen. Vergleich #86 

- [ ] Randomisierung entfernen und nur Daten Nachname, Krankenkasse, Versichertennr, E-Mail, Telefon, Straße, Hausnr bei absenden in ****** ändern

**Comment by Seal33** [comment]
>  Bei multiple-Coice-Fragen in Infektionskette, Symptome Option "keine" hinzufügen
Man kann doch einfach nichts ankreuzen, oder?

> Randomisierung entfernen und nur Daten Nachname, Krankenkasse, Versichertennr, E-Mail, Telefon, Straße, Hausnr bei absenden in ****** ändern
Den ersten Buchstaben würde ich beibehalten, damit man sieht, dass es funktioniert hat (zB aus Musterstraße wird M********

Was passiert am Ende mit den (selbst)eingereichten Verdachtsfällen? Die Müssten doch irgendwo erfasst und fortführend verarbeitet werden... wer bewertet sie in bezug aufs weitere vorgehen?


Ich finde Selbsterfassung ist ein wichtiges Feature, aber ich würde nochmal besprechen, ob wir das bis freitag einführen wollen... mit der sorge, dass dabei inhaltliche lücken entstehen könnten

**Comment by t0bska** [comment]
> Man kann doch einfach nichts ankreuzen, oder?

Soll verhindern, dass ich das als Patient übersehe

>Den ersten Buchstaben würde ich beibehalten, damit man sieht, dass es funktioniert hat (zB aus Musterstraße wird M********

macht Sinn

>Was passiert am Ende mit den (selbst)eingereichten Verdachtsfällen? ...

Die vom Arzt angelegten sollen automatisch als Verdachtsfall eingestuft werden in der Datenbank (die müsste dafür schon vorbereitet sein)

>Ich finde Selbsterfassung ist ein wichtiges Feature, aber ich würde nochmal besprechen, ob wir das bis freitag einführen wollen... mit der sorge, dass dabei inhaltliche lücken entstehen könnten

Falls zeitlich nicht zu schaffen, würde ich die automatische Einstufung als Verdachtsfall (s.o.) weglassen, UI aber trotzdem Hinbauen, zeigt, dass wir das bedacht haben. Bei der Orga-Besprechung eben bestand große Einigkeit darüber, dass das extrem wichtig ist

**Comment by Seal33** [comment]
Okey das macht Sinn. Ich bin dennoch der meinung, dass das jetzt etwas überhastet ist. Ich finde das ebenfalls sehr wichtig, aber weiß nicht, ob für Freitag nicht ein hinweis reicht dass wir da dran arbeiten. Was passiert mit Verdachtsfällen? Bleiben die einfach so in der Datenbank und nichts weiter passiert? Irgendjemand muss sich die selbst-registrierten Verdachtsfälle doch ansehen und bewerten. Wieso können Ärzte keinen Test mehr anordnen (oder passiert das jetzt wo anders)?

Irgendwo müssten Ärzte doch eine Liste mit abzuarbeitenden selbst-registrierung bekommen. Dann besteht allerdings die frage, welcher arzt welche Fälle angezeigt bekommt.

Wenn ihr das besprochen habt können wir das schon machen, ich versuche nur noch das System dahinter zu verstehen

**Comment by t0bska** [comment]
>Wieso können Ärzte keinen Test mehr anordnen (oder passiert das jetzt wo anders)? 

Das soll über die Patienten-Seite geschehen.

>ob für Freitag nicht ein hinweis reicht dass wir da dran arbeiten

**Man könnte durchaus noch überlegen, die Seite "Unterstützte Selbsteinschätzung" zwar anzulegen, aber nur einen kurzen Text reinzuschreiben, dass daran noch gearbeitet wird. Denn die jetzt angedachte Version ist auch nur eine Notlösung.**

> Irgendjemand muss sich die selbst-registrierten Verdachtsfälle doch ansehen und bewerten.

Soll mit Filter auf der Seite mit allen Patienten möglich sein.

Es ist alles keine 1000% geile Lösung, man könnte durchaus noch ein Feld "Test anordnen -> Ja/Nein" bei der Registrierung durch Arzt hinzufügen, aber das macht halt auch wieder Aufwand.

**Comment by Seal33** [comment]
> Man könnte durchaus noch überlegen, die Seite "Unterstützte Selbsteinschätzung" zwar anzulegen, aber nur einen kurzen Text reinzuschreiben, dass daran noch gearbeitet wird. Denn die jetzt angedachte Version ist auch nur eine Notlösung.

Das halte ich für sinnvoll, und kommt glaube ich auch besser an. Es erwartet ja niemand, dass wir ein komplett fertiges produkt abliefern, die wollen bloß einen Prototypen sehen

> Soll mit Filter auf der Seite mit allen Patienten möglich sein.

Okey macht Sinn. Bleibt noch zu klären wem welche Patienten zugeordnet werden

>man könnte durchaus noch ein Feld "Test anordnen -> Ja/Nein" bei der Registrierung durch Arzt hinzufügen, aber das macht halt auch wieder Aufwand.

Hatten wir ja im Grunde früher auch schon und würde ich auch wieder einfügen. Denke der Aufwand dafür ist Minimal

**Comment by t0bska** [comment]
> Das halte ich für sinnvoll, und kommt glaube ich auch besser an. Es erwartet ja niemand, dass wir ein komplett fertiges produkt abliefern, die wollen bloß einen Prototypen sehen

Dann machen wir das so. Da sollte dann vom Inhalt her folgendes stehen:
- Hier wird noch dran gearbeitet
- Patienten können hier eine Computergestützte Selbsteinschätzung vornehmen und dann ggf. ihre persönlichen Daten gemeinsam mit den Daten aus der Selbsteinschätzung an das Gesundheitsamt übermitteln
- Verdachtsfälle können hier ihre Kontaktpersonen eintragen, sodass diese bei positivem Testergebnis automatisch kontaktiert werden können

**Comment by Seal33** [comment]
Closed for now.
