### ISSUE TITLE
GUI "Patienten-Daten"

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#86]
Todo:
- [x] Stammdaten des Patienten anzeigen
- [x] Option Test anordnen hinzufügen
- [ ] Anzeige Patientenstatus hinzufügen: Verdachtsfall / kein Verdachtsfall / genesen / verstorben / intensivmedizinische behandlung start / ende (soll als eigenes Event mit Timestamp in Datenbank gespeichert werden)
- [ ] Quarantäne-Status anzeigen
- [ ] *jegliche* Änderungen, und Tests (Anordnung+Probe+Ergebnis) in Timeline anzeigen
- [ ] Test erneut anordnen doch wieder entfernen

**Comment by t0bska** [comment]
outdated needs to be reworked

**Comment by wobkenh** [comment]
Kommt gleich nach Staging:
- Suchleiste in der Navbar zum Suchen von Patienten eingebaut
- Mehr Patientendetails (z.B. Vorerkrankungen, Arbeitgeber)
- Tabelle mit Tests zu diesem Patienten
- Die Status im Verlauf wurden schon in einem anderen Issue mal angepasst.
- "Test erneut anfordern" Button entfernt

- Quarantänestatus ==> Dieses bitte in einem neuen Ticket näher beschreiben, weil das gibt es aktuell noch gar nicht und da bräuchte ich mehr Infos zu

**Comment by JonasCir** [comment]
CC #179

**Comment by wobkenh** [comment]
Denke das Issue hier ist dann durch?
