### ISSUE TITLE
GUI "Test Zuordnen": Test-Typ-Auswahl hinzufügen

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#87]
Todo:
- [x] Laboranmeldung entfernen

- [x] Feld "Labor" hinzufügen mit einem Dummy-Labor zur Auswahl 

- [x] Select "Test-Typ" hinzufügen. Optionen: PCR, Antikörpertest 

- [x] Randomisierung entfernen

**Comment by Seal33** [comment]
Warum soll hier ein Labor ausgewählt werden?

**Comment by t0bska** [comment]
Da die Proben-ID nur für ein Labor spezifisch ist. Das Labor muss irgendwie erfasst werden. Muss fürs erste keine Backend-Funktionalität haben, wenn nur ein Labor zur Auswahl steht.

**Comment by wobkenh** [comment]
> "Feld "Labor" hinzufügen mit einem Dummy-Labor zur Auswahl"

Macht das überhaupt Sinn? Ist nicht anhand des Users klar, woher der Test kommt? (Ein User = gehört zu einem Labor = kann nur Tests in seinem Labor anlegen / zuordnen)
Oder habe ich da was am Prozess nicht richtig verstanden?

**Comment by t0bska** [comment]
Nein, eine Teststation kann an mehrere Labore liefern. Das Testergebnis wird zunächst wahrscheinlich das Gesundheitsamt eintragen, das ist aber noch nicht sicher.

**Comment by wobkenh** [comment]
Ich habe meine Anpassungen zu Probe zuordnen / Testresultat zuordnen mal auf Dev gepushed.

Bin für Feedback offen. Ansonsten kann das Issue geschlossen werden.

**Comment by t0bska** [comment]
Für's erste passt das. Mit dem Gesundheitsamt zusammen muss man das ggf. nochmal feiner spezifizieren
