### ISSUE TITLE
GUI "Testresultat Zuordnen"

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#88]
Todo:

- [x] Laboranmeldung entfernen

- [x] Laborauswahl hinzufügen mit einem Dummy-Labor zur Auswahl (demselben, wie in #87 )

- [x] Randomisierung entfernen

**Comment by Seal33** [comment]
Warum wird die Laboranmeldung entfernt?

**Comment by t0bska** [comment]
Das soll irgendwann über eine Zentrale Anmeldemaske passieren, siehe #38 #73. (Die wird fürs erste auch nur Clientseitig mit einer Dummy-Anmeldemaske erfolgen.) Meldet man sich mit Labor-Zugangsdaten an, bekommt man dann den Labor-Teil angezeigt, wie z.B. auch als Arzt. Das Permission-Zeug kann man aber später hinzufügen.

**Comment by wobkenh** [comment]
Ich habe jetzt folgende Dinge angepasst:
- Textfeld für die TestId ist jetzt ein Autocomplete, d.h. während des Tippens werden verfügbare TestIds vorgeschlagen
- Auswahl der Test-Ergebnisse an das angepasst, was im Backend definiert ist
- LaborId entfernt (Siehe Frage bei #87)

Wäre schön, wenn mir jemand die Frage bei #87 beantworten könnte.
Ansonsten setze ich das so wie ich das hier gemacht habe morgen auch bei #87 um und merge #87 und #88 auf dev.

**Comment by t0bska** [comment]
seems to be done
