### ISSUE TITLE
GUI "Alle Patienten"

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#89]
- [x] Alle Patienten auflisten mit Daten wie bisher in alle Patienten
- [x] Zusätzlich letzten Patientenstatus und Testergebnis anzeigen (vergleiche #86 )
- [x] mit Doppelklick auf Eintrag führt zum Patienten im UI "Patienten-Daten"
- [x] CSV-Export mit Leben füllen
- [x] Filteroption nach Patientenstatus und Testergebnis einbauen (erstmal Clientseitig)
- [x] Suche mit Leben Füllen (erstmal Clientseitig)

**Comment by bmikaili** [comment]
Kann das zu?

**Comment by t0bska** [comment]
closed
