### ISSUE TITLE
GUI "Öffentliche Statistiken"

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#90]
Todo:
- [ ] Umbenennen in Statistiken (RKI)
- [ ] Funktional machen

**Comment by Jochen-Sch** [comment]
Vorschlag : "Statistiken" (ohne RKI) da Statistiken auf Kreis, Landes und Bundesebene relevant sind

**Comment by t0bska** [comment]
closed because of unclear use case. GUI can be removed.
