### ISSUE TITLE
Patienten ID = Die Patienten ID lautet: c40d310327687e9cfd27001e595629ea6fadda9495a237bae6d04f8168a6bdce

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#94]
Bitte in Nummer ändern die sich ein Patient auch merken oder aufschreiben kann ... der Prozess muss auch ohne QR gehen!

**Comment by Seal33** [comment]
Netterweise können wir ja davon ausgehen dass höchstens  ~80 Millionen Patienten (sagen wir mit puffer 100) in der Datenbank landen. Also sollten bei hexadezimal schon 7 stellen ausreichen 
(FFFFFFF_16 = 268.435.455_10). Wenn man ganz sicher gehen will kommt man mit 8 stellen für immer hin.

Ist natürlich dann die fragen, wie man sowas hashen kann, da hab ich leider nicht so viel Erfahrung. Aber 64 stellen ist definitiv zu viel.

**Comment by jojo19893** [comment]
jep so lange wir keine zahlen nehmen ist mir das egal :D

**Comment by luxn** [comment]
soetwas könnt eine Lösung darstellen:
https://hashids.org/

**Comment by jojo19893** [comment]
oder so was: https://neilmadden.blog/2018/08/30/moving-away-from-uuids/

**Comment by t0bska** [comment]
seems to be fixed
