### ISSUE TITLE
"Ergebnis Zuordnen" endet mit 404

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#96]
Prototype broken

**Comment by jonathangpk** [comment]
Es funktioniert, der prozess ist aber zu aufwändig und unverständlich

man muss eine labor Institution erstellen, die ID als anmelde name fürs labor verwendne, einen patienten erstellen und die ID als patienten ID nehmen, bei test registrieren eine beliebige test id eintragen. Bei Test zuordnen wieder mit der labor id anmelden und  die proben ID von vorher eintragen mit ergebnis. Dann gibt es auch keine 404

**Comment by jonathangpk** [comment]
Ich close es und erstelle ein Issue das sich mit einem einfacherem prozess fuer die demo beschaeftigt
